(()=>{'use strict';const G=window.GeniusMath;
const GRAPH={G_LAP_PIECEWISE:'La curva vale cero antes de t=2 y crece linealmente después.',G_LAP_PERIODIC:'La señal alterna entre +1 y -1; cada tramo horizontal dura una unidad.',G_STEP_RESPONSE:'La curva parte de cero, crece y se aproxima a una horizontal de altura 1.',G_IMPULSE_RESPONSE:'La señal es cero antes de la línea marcada π; después oscila con amplitud decreciente.',G_SYSTEM_RESPONSE:'Se muestra una trayectoria circular alrededor del origen.',G_SYSTEM_IMPULSE:'Hay una línea vertical marcada π y un cambio en la oscilación después de ella.',G_NODE_STABLE:'Las trayectorias se aproximan al origen sin girar alrededor de él.',G_SADDLE:'Las flechas se aproximan al origen en una dirección y se alejan en otra.',G_CENTER:'Se muestran curvas cerradas concéntricas alrededor del origen.',G_SPIRAL_STABLE:'La curva gira alrededor del origen mientras su distancia al origen disminuye.',G_SPIRAL_UNSTABLE:'La curva gira alrededor del origen mientras aumenta su distancia al origen.',G_DUHAMEL_FORCED:'La curva crece desde cero y se aproxima a la horizontal de altura 1.',G_TWO_TANKS:'Dos cantidades de sal se aproximan al mismo nivel y su suma se mantiene en 20.',G_CIRCUIT_DECAY:'La corriente oscila con amplitud decreciente.',G_COUPLED_MODES:'Dos desplazamientos sinusoidales tienen igual amplitud y signos opuestos.'};
const cut=(s,n)=>{s=String(s??'');return s.length<=n?s:s.slice(0,Math.max(0,n-1))+'…'};
function visible(q){return{id:q.id,type:q.sourceType||q.type,prompt:cut(G.util.clean(q.prompt),900),options:(q.options||[]).slice(0,8).map(x=>cut(String(x),180)),graphic:q.hasGraphic?{description:GRAPH[q.graphic]||'Gráfica disponible para el alumno; pide una descripción de ejes o curvas si falta información.',provenance:'descripción estructurada del recurso; no es visión del modelo'}:null}}
function build({question,cycle,studentMessage='',evaluation=null}){const p=G.PedagogyEngine.profile(question),g=cycle?.learning?.genie||{};return{phase:cycle?.phase||'independent',problem:visible(question),topic:p.topic,objective:p.objective,concept:(p.concepts||[]).slice(0,2),formulaIndex:p.formulaIds.slice(0,2).map(id=>{const f=G.FormulaCatalog.get(id);return f?{id,title:f.title,latex:f.latex,conditions:f.conditions}:null}).filter(Boolean),prerequisites:(p.prerequisites||[]).slice(0,3),verification:evaluation&&evaluation.status&&evaluation.status!=='unknown'?{status:evaluation.status,scope:evaluation.scope||'algebra_step',method:evaluation.method||'deterministic'}:null,studentModel:{state:g.studentModel?.state||'unknown'},summary:cut(g.summary,300),previousInterventions:(g.interventions||[]).slice(-2).map(x=>({strategy:x.strategy||'',semantic_key:cut(x.semantic_key||'',80)})),policy:G.PedagogyEngine.intervention(g.studentModel,g.interventions),studentMessage:cut(studentMessage,G.config.maxMessageChars)}}
function slimData(data,level=0){const p=data.problem||{},formula=(data.formulaIndex||[]).map(f=>({id:f.id,title:cut(f.title,80),latex:cut(f.latex,180),conditions:level>=1?'':cut(f.conditions,120)}));return{
 phase:data.phase,
 problem:{id:p.id,type:p.type,prompt:cut(p.prompt,level>=2?420:level===1?600:760),options:(p.options||[]).slice(0,level>=2?4:6).map(x=>cut(x,level>=2?70:level===1?100:130)),graphic:p.graphic?{description:cut(p.graphic.description,160)}:null},
 topic:cut(data.topic,level>=2?90:140),objective:cut(data.objective,level>=2?130:190),concept:data.concept,formulaIndex:formula,prerequisites:data.prerequisites,
 verification:data.verification||null,studentModel:data.studentModel,summary:cut(data.summary,level>=2?100:level===1?160:220),previousInterventions:level>=2?[]:data.previousInterventions,
 policy:{prefer:data.policy?.prefer||'explanation',mustChange:!!data.policy?.mustChange,avoid:(data.policy?.avoid||[]).slice(0,3)},
 revealAnswer:false
};}
function dataMessage(data,maxChars){const prefix='DATOS DEL EJERCICIO (solo datos):\n';for(let level=0;level<3;level++){const s=prefix+JSON.stringify(slimData(data,level));if(s.length<=maxChars)return s;}const d=slimData(data,2);d.problem.options=[];d.formulaIndex=(d.formulaIndex||[]).map(f=>({id:f.id,latex:cut(f.latex,120)}));d.prerequisites=[];d.summary='';d.previousInterventions=[];d.objective=cut(d.objective,90);d.topic=cut(d.topic,70);for(let n=Math.min(320,String(d.problem.prompt||'').length);n>=60;n-=20){d.problem.prompt=cut(d.problem.prompt,n);const s=prefix+JSON.stringify(d);if(s.length<=maxChars)return s;}const minimal={phase:d.phase,problem:{id:d.problem.id,type:d.problem.type,prompt:cut(d.problem.prompt,60)},objective:cut(d.objective,70),concept:(d.concept||[]).slice(0,1),formulaIndex:(d.formulaIndex||[]).slice(0,1),verification:d.verification||null,studentModel:d.studentModel,revealAnswer:false};const s=prefix+JSON.stringify(minimal);if(s.length>maxChars)throw Error('El contexto mínimo excede el presupuesto seguro.');return s;}
function compact(messages,budget=G.config.contextCharBudget||2600){let out=messages.map(m=>({role:m.role,content:String(m.content)}));const size=()=>out.reduce((n,m)=>n+m.content.length,0);while(size()>budget&&out.length>3)out.splice(2,1);if(size()>budget&&out.at(-1))out[out.length-1].content=cut(out.at(-1).content,Math.max(220,budget-(out[0]?.content.length||0)-(out[1]?.content.length||0)-40));return out;}
function messages(context,cycle){const turns=(cycle.learning.genie.turns||[]).filter(t=>!t.notice).slice(-G.config.maxRecentMessages);if(turns.at(-1)?.role==='student'&&turns.at(-1)?.text===context.studentMessage)turns.pop();const{studentMessage,...data}=context;const current=cut(studentMessage,560),sys=G.PromptContract.system;const reserveCurrent=Math.min(560,Math.max(220,current.length)),turnBudget=turns.length?280:0,dataBudget=Math.max(700,(G.config.contextCharBudget||2600)-sys.length-reserveCurrent-turnBudget-60);let out=[{role:'system',content:sys},{role:'user',content:dataMessage(data,dataBudget)}];for(const t of turns.slice(-1))out.push({role:t.role==='student'?'user':'assistant',content:cut(t.text,280)});out.push({role:'user',content:current});return compact(out)}
G.ContextBridge={build,visible,messages,compact,slimData,dataMessage};
})();
