/* Bounded IndexedDB operations; transcript failure never stalls grading or Poker. */
(()=>{'use strict';const G=window.GeniusMath,DB='PokerEDOGeniusGenerativeV72';let dbPromise=null;const queues=new Map();
function open(){if(!globalThis.indexedDB)return Promise.reject(Error('IndexedDB no disponible'));if(dbPromise)return dbPromise;
 const pending=new Promise((resolve,reject)=>{let request,done=false;const end=(error,db)=>{if(done){db?.close();return}done=true;clearTimeout(timer);if(error)reject(error);else resolve(db)};const timer=setTimeout(()=>end(Error('IndexedDB no respondió a tiempo.')),4000);
 try{request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('threads'))db.createObjectStore('threads',{keyPath:'id'});if(!db.objectStoreNames.contains('events'))db.createObjectStore('events',{keyPath:'id',autoIncrement:true})};request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>{db.close();dbPromise=null};end(null,db)};request.onerror=()=>end(request.error||Error('IndexedDB rechazó la apertura.'));request.onblocked=()=>end(Error('IndexedDB bloqueado por otra conexión.'))}catch(e){end(e)}});
 dbPromise=pending.catch(e=>{dbPromise=null;throw e});return dbPromise;
}
async function transaction(store,mode,fn){const db=await open();return new Promise((resolve,reject)=>{let tx,done=false,result;const end=(error)=>{if(done)return;done=true;clearTimeout(timer);error?reject(error):resolve(result)};const timer=setTimeout(()=>{try{tx?.abort()}catch(_){}end(Error('La transacción de memoria superó el límite de espera.'))},4000);try{tx=db.transaction(store,mode);const req=fn(tx.objectStore(store));if(req)req.onsuccess=()=>{result=req.result};tx.oncomplete=()=>end();tx.onerror=()=>end(tx.error||Error('Error de memoria local.'));tx.onabort=()=>end(tx.error||Error('Transacción cancelada'))}catch(e){end(e)}})}
async function load(id){try{return await transaction('threads','readonly',s=>s.get(id))||null}catch(e){G.GenieMemory.lastError=e.message;return null}}
async function save(id,data){const previous=queues.get(id)||Promise.resolve();const job=previous.catch(()=>{}).then(async()=>{const old=await load(id);const byId=new Map((old?.turns||[]).map(t=>[t.id||`${t.at}:${t.role}:${t.text}`,t]));for(const t of data.turns||[])byId.set(t.id||`${t.at}:${t.role}:${t.text}`,t);const thread={...old,...data,id,turns:[...byId.values()].sort((a,b)=>a.at-b.at),updatedAt:Date.now()};await transaction('threads','readwrite',s=>s.put(thread));return true}).catch(e=>{G.GenieMemory.lastError=e.message;return false});queues.set(id,job);job.finally(()=>{if(queues.get(id)===job)queues.delete(id)});return job}
async function record(event){try{await transaction('events','readwrite',s=>s.add({...event,at:event.at||Date.now()}));return true}catch(e){G.GenieMemory.lastError=e.message;return false}}
G.GenieMemory={load,save,record,flush:()=>Promise.all([...queues.values()]),lastError:null};})();
