/* v7.2.2: conservative capability checks. No weights, no attempt and no grade writes. */
(()=>{'use strict';const G=window.GeniusMath;
const labels={origin:'HTTPS / localhost',systemMemory:'Memoria del equipo',resourceRisk:'Margen de almacenamiento',secureContext:'Contexto seguro',webgpu:'WebGPU',adapter:'Adaptador GPU',f16:'Precisión f16 segura',worker:'Worker de inferencia',workerF16:'f16 dentro del Worker',indexedDB:'IndexedDB · escribir / leer / borrar',storage:'Espacio del navegador',persistence:'Persistencia de almacenamiento',online:'Conectividad',iframe:'Entorno / iframe',policy:'Políticas detectables',runtime:'Runtime JavaScript',modelConfig:'Servidor y configuración del modelo'};
const now=()=>performance.now();
function withTimeout(promise,ms,label,signal){return new Promise((resolve,reject)=>{let done=false;const end=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);fn(v)};const abort=()=>end(reject,G.util.abortError());const timer=setTimeout(()=>end(reject,Object.assign(Error(label+' no respondió a tiempo.'),{code:'TIMEOUT'})),ms);if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});Promise.resolve(promise).then(v=>end(resolve,v),e=>end(reject,e))})}
function idbTest(idb,{timeoutMs=5000,signal}={}){return new Promise((resolve,reject)=>{let db=null,done=false,request=null;const name=G.util.id('GeniusCapabilityProbe');
 const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);try{db?.close();idb?.deleteDatabase(name)}catch(_){}error?reject(error):resolve(value)};
 const abort=()=>finish(G.util.abortError());const timer=setTimeout(()=>finish(Error('IndexedDB no respondió (bloqueo o espera de apertura).')),timeoutMs);
 if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});try{if(!idb)throw Error('IndexedDB no está disponible.');request=idb.open(name,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('probe'))request.result.createObjectStore('probe')};request.onerror=()=>finish(request.error||Error('No se pudo abrir IndexedDB.'));request.onblocked=()=>finish(Error('IndexedDB está bloqueado por otra conexión o una política.'));request.onsuccess=()=>{db=request.result;if(done){db.close();idb.deleteDatabase(name);return}try{const tx=db.transaction('probe','readwrite'),store=tx.objectStore('probe');store.put('real-probe','key');const read=store.get('key');let matched=false,deleted=false;read.onsuccess=()=>{matched=read.result==='real-probe';store.delete('key');const after=store.get('key');after.onsuccess=()=>{deleted=after.result===undefined}};tx.onerror=()=>finish(tx.error||Error('IndexedDB rechazó la transacción.'));tx.onabort=()=>finish(tx.error||Error('IndexedDB abortó la transacción.'));tx.oncomplete=()=>matched&&deleted?finish(null,{open:true,write:true,read:true,delete:true}):finish(Error('La lectura/borrado de prueba no coincide.'))}catch(e){finish(e)}}}catch(e){finish(e)}})}
function workerTest(url,{timeoutMs=12000,signal}={}){return new Promise((resolve,reject)=>{let worker=null,done=false;const end=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);worker?.terminate();fn(v)};const abort=()=>end(reject,G.util.abortError());const timer=setTimeout(()=>end(reject,Error('El Worker no confirmó su inicio. Revisa worker-src, la ruta y el tipo MIME.')),timeoutMs);if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});try{worker=new Worker(url,{type:'module',name:'GeniusCapabilityProbe'});worker.onmessage=e=>{const expected=G.config.workerProbeVersion||'7.2.2.2';if(e.data?.probeVersion===expected)end(resolve,e.data);else if(e.data?.probeVersion)end(reject,Object.assign(Error('El Worker respondió con una versión antigua ('+e.data.probeVersion+'); se esperaba '+expected+'. Actualiza la página y la caché del sitio.'),{code:'WORKER_VERSION_MISMATCH'}))};worker.onerror=e=>end(reject,Object.assign(Error((e.message||'Creación/carga del Worker bloqueada.')+' URL: '+url+(e.filename?' · '+e.filename+':'+(e.lineno||0):'')),{code:'WORKER_LOAD_ERROR'}));worker.onmessageerror=()=>end(reject,Object.assign(Error('El navegador no pudo decodificar la respuesta del Worker. URL: '+url),{code:'WORKER_MESSAGE_ERROR'}));worker.postMessage({type:'probe'})}catch(e){end(reject,e)}})}
function recommendProfile(cap){const available=Object.keys(G.config.profiles||{}),fallback=available.includes('light')?'light':available[0]||null;return{profile:fallback,rule:G.config.safeMode?'safe_mode_only_available_profile':'available_profile',kind:'conservative_hardware_trial_not_quality_selection',recommendedDefault:null,inputs:{deviceMemoryGB:cap.deviceMemoryGB??null,limits:cap.adapter?.limits||{},availableBytes:cap.storage?.availableBytes??null},reason:G.config.safeMode?'Modo de estabilidad: solo se ofrece el perfil ligero auditado; no se escalan modelos automáticamente.':'Solo se recomienda un perfil incluido en esta compilación.',policy:'SAFE_GPU_POLICY_V722'};}
async function probe({signal,onCheck,worker=true}={}){const start=now(),n=navigator,checks=[];const report={version:G.config.version,kind:'actual_browser_capability_probe',executed:true,at:new Date().toISOString(),environment:{protocol:location.protocol,origin:location.origin,secureContext:!!globalThis.isSecureContext,topEqualsSelf:window.top===window.self,userAgent:n.userAgent,platform:n.userAgentData?.platform||n.platform||null},deviceMemoryGB:typeof n.deviceMemory==='number'?n.deviceMemory:null,adapter:null,storage:null,checks};
 const add=(id,status,message,{required=false,value=null,code=id.toUpperCase(),impact='',remedy=''}={})=>{const x={id,label:labels[id]||id,status,message,required,code,value,impact,remedy,continueWithoutAI:true};checks.push(x);onCheck?.(x,report);return x};
 const loopback=['localhost','127.0.0.1','[::1]'].includes(location.hostname);const valid=location.protocol==='https:'||(location.protocol==='http:'&&loopback);
 add('origin',valid?'pass':'fail',valid?'Página servida por HTTPS o localhost.':location.protocol==='file:'?'Esta página se abrió como archivo local (file://).':'El origen no es HTTPS ni localhost.',{required:true,code:location.protocol==='file:'?'FILE_PROTOCOL':'UNSUPPORTED_ORIGIN',impact:'El runtime modular y el almacenamiento del modelo necesitan un origen web válido.',remedy:'Usa HTTPS (GitHub Pages/Brightspace) o localhost. No abras index.html con doble clic.'});
 add('secureContext',globalThis.isSecureContext?'pass':'fail',globalThis.isSecureContext?'El navegador reconoce un contexto seguro.':'El navegador no reconoce un contexto seguro.',{required:true,remedy:'Usa HTTPS o localhost; en Brightspace revisa también el contexto del iframe.'});
 const mem=report.deviceMemoryGB;if(typeof mem==='number'){const ok=mem>=8;add('systemMemory',ok?'pass':'fail',ok?`El navegador informa ${mem} GB o más en su estimación de memoria.`:`El navegador informa ${mem} GB; el modo LLM local se bloquea de forma conservadora.`,{required:!ok,code:'LOW_SYSTEM_MEMORY_SAFE_MODE',impact:'Un modelo WebGPU puede competir con el navegador y el sistema por memoria compartida.',remedy:ok?'':'Usa la Guía compatible o prueba otro equipo. No fuerces modelos mayores.'})}else add('systemMemory','warning','El navegador no expone navigator.deviceMemory; no se puede estimar RAM disponible.',{code:'SYSTEM_MEMORY_UNKNOWN',remedy:'La prueba seguirá con límites conservadores; si el equipo ya mostró pantalla negra, no uses IA local.'});
 add('webgpu',n.gpu?'pass':'fail',n.gpu?'La API WebGPU está expuesta.':'Este navegador no expone navigator.gpu.',{required:true,code:'WEBGPU_UNAVAILABLE',impact:'No se puede ejecutar el proveedor local WebGPU.',remedy:'Usa un navegador actualizado con aceleración gráfica habilitada o continúa con la Guía compatible.'});
 try{if(!n.gpu)throw Error('WebGPU no está disponible.');const a=await withTimeout(n.gpu.requestAdapter(),7000,'Adaptador GPU',signal);if(!a)throw Error('requestAdapter() devolvió null.');const keys=['maxBufferSize','maxStorageBufferBindingSize','maxComputeWorkgroupStorageSize','maxComputeInvocationsPerWorkgroup','maxComputeWorkgroupSizeX','maxStorageBuffersPerShaderStage'];report.adapter={obtained:true,f16:a.features.has('shader-f16'),limits:Object.fromEntries(keys.map(k=>[k,a.limits[k]??null])),info:a.info?{vendor:a.info.vendor||null,architecture:a.info.architecture||null,isFallbackAdapter:a.info.isFallbackAdapter??null}:null};const fallback=report.adapter.info?.isFallbackAdapter===true;add('adapter',fallback?'fail':'pass',fallback?'El navegador reporta un adaptador GPU de respaldo/software; no se usará para el LLM local.':'Adaptador obtenido; se comprobará también dentro del Worker.',{required:true,code:fallback?'GPU_FALLBACK_ADAPTER':'ADAPTER_OK',value:report.adapter,impact:fallback?'La inferencia sostenida sobre un adaptador de respaldo puede ser inestable o extremadamente lenta.':'',remedy:fallback?'Usa la Guía compatible o un equipo con adaptador WebGPU de hardware.':''})}catch(e){if(e.name==='AbortError')throw e;add('adapter','fail','No se obtuvo un adaptador: '+e.message,{required:true,code:'ADAPTER_UNAVAILABLE',remedy:'Revisa aceleración gráfica, controladores y políticas del navegador.'})}
 if(G.config.localModel.requireF16){const ok=report.adapter?.f16===true;add('f16',ok?'pass':'fail',ok?'shader-f16 disponible: se usará la variante ligera q4f16.':'Este modo seguro no cargará la variante f32, que consume más memoria.',{required:true,code:'F16_REQUIRED_SAFE_MODE',impact:'Se evita una ruta de mayor consumo en un equipo sin shader-f16.',remedy:'Continúa con la Guía compatible o prueba otro equipo con shader-f16.'})}
 try{if(!worker)throw Error('Prueba de Worker omitida explícitamente.');const w=await workerTest(G.config.localModel.probeWorker,{signal});report.worker=w;if(!w.adapterObtained)throw Error(w.error||'El Worker inició, pero no obtuvo adaptador WebGPU.');add('worker','pass','Worker modular y adaptador en el Worker confirmados por ida y vuelta.',{required:true,value:{...w,url:G.config.localModel.probeWorker}})}catch(e){if(e.name==='AbortError')throw e;add('worker',worker?'fail':'unknown',e.message,{required:true,code:e.code||'WORKER_UNAVAILABLE',value:{url:G.config.localModel.probeWorker},remedy:'Haz una recarga fuerte. Si persiste, verifica que la URL del Worker abra como JavaScript y que GitHub Pages haya desplegado la versión actual.'})}
 if(G.config.localModel.requireF16&&report.worker){const ok=report.worker.f16===true;add('workerF16',ok?'pass':'fail',ok?'El Worker también confirma shader-f16.':'El Worker no confirmó shader-f16.',{required:true,code:'WORKER_F16_REQUIRED',impact:'No se inicia el LLM local en esta ruta segura.',remedy:'Continúa con la Guía compatible o prueba otro equipo.'})}
 try{const val=await idbTest(globalThis.indexedDB,{signal});add('indexedDB','pass','Apertura, escritura, lectura y borrado temporal comprobados.',{required:true,value:val})}catch(e){if(e.name==='AbortError')throw e;add('indexedDB','fail',e.message,{required:true,code:'INDEXEDDB_BLOCKED',impact:'No se puede garantizar almacenamiento de pesos y conversación.',remedy:'Permite almacenamiento para este origen. Revisa modo privado y restricciones del iframe.'})}
 try{if(!n.storage?.estimate)throw Error('StorageManager.estimate no disponible.');const x=await withTimeout(n.storage.estimate(),4000,'Cuota',signal);report.storage={quota:x.quota??null,usage:x.usage??null,availableBytes:Number.isFinite(x.quota)&&Number.isFinite(x.usage)?Math.max(0,x.quota-x.usage):null};add('storage','pass','Cuota estimada del origen, no memoria RAM ni VRAM.',{value:report.storage})}catch(e){if(e.name==='AbortError')throw e;add('storage','unknown',e.message,{code:'STORAGE_ESTIMATE_UNAVAILABLE',remedy:'La carga seguirá sujeta al espacio que conceda el navegador.'})}
 const safeProfile=G.config.profiles?.[G.config.localModel.profile]||Object.values(G.config.profiles||{})[0];const need=Number(safeProfile?.downloadEstimateBytes)||0;if(report.storage?.availableBytes!=null&&need>0){const ratio=report.storage.availableBytes/need;const ok=ratio>=1.5;add('resourceRisk',ok?(ratio<2.5?'warning':'pass'):'fail',ok?`Hay margen estimado de almacenamiento de ${ratio.toFixed(1)}× la descarga prevista.`:'El margen estimado del origen es menor que 1,5× la descarga prevista.',{required:!ok,code:'LOW_STORAGE_MARGIN',value:{availableBytes:report.storage.availableBytes,downloadEstimateBytes:need,ratio},impact:ok?'':'La descarga/caché puede fallar o ser desalojada durante la preparación.',remedy:ok?'Conserva espacio libre; el navegador decide la cuota final.':'Libera espacio o usa la Guía compatible.'})}
 try{if(!n.storage?.persisted)throw Error('API de persistencia no disponible.');const value=await withTimeout(n.storage.persisted(),3000,'Persistencia',signal);add('persistence',value?'pass':'warning',value?'El origen tiene almacenamiento persistente.':'Caché no persistente: el navegador puede desalojarla.',{value,remedy:'Puedes solicitar persistencia desde el panel; el navegador decide.'})}catch(e){if(e.name==='AbortError')throw e;add('persistence','unknown',e.message)}
 add('online',n.onLine===false?'warning':'pass',n.onLine===false?'El navegador declara estar sin conexión.':'El navegador declara conexión; esto no prueba acceso a los servidores.',{value:n.onLine??null,code:'OFFLINE',remedy:'La primera descarga necesita red. Una caché parcial no garantiza ejecución sin conexión.'});
 let parentOrigin=null;try{parentOrigin=window.parent.location.origin}catch(_){parentOrigin='cross-origin: no accesible'}report.environment.parentOrigin=parentOrigin;
 add('iframe',window.top===window.self?'pass':'warning',window.top===window.self?'Pestaña independiente.':'Actividad en iframe: no se intentará salir del reproductor.',{value:{...report.environment},remedy:'Compara el diagnóstico en una pestaña y en el reproductor LMS.'});
 let policies={inspectionAvailable:false,webgpuPolicy:null,sandbox:null};try{const p=document.permissionsPolicy||document.featurePolicy;const known=p?.features?.();if(known){policies.inspectionAvailable=true;if(known.includes('webgpu'))policies.webgpuPolicy=p.allowsFeature('webgpu')}policies.sandbox=window.frameElement?.getAttribute('sandbox')??null}catch(_){}report.policies=policies;
 add('policy',policies.webgpuPolicy===false?'fail':'unknown',policies.webgpuPolicy===false?'Una política detectable impide WebGPU.':'CSP y políticas del padre no siempre son legibles; se registrarán los bloqueos observados.',{value:policies,required:policies.webgpuPolicy===false,remedy:'Revisa consola, CSP, WebAssembly y permisos efectivos si la preparación falla.'});
 add('runtime','unknown','Se importará y comprobará después de autorizar la preparación; aún no se han descargado pesos.',{code:'RUNTIME_PENDING'});add('modelConfig','unknown','El acceso a configuración y servidor de pesos se comprobará durante la preparación.',{code:'MODEL_RESOURCES_PENDING'});
 report.supported=checks.filter(x=>x.required).every(x=>x.status==='pass');report.recommendation=recommendProfile(report);report.durationMs=now()-start;report.measurementUnavailableReason={freeVRAM:'WebGPU no expone una medida portátil de VRAM libre.',peakMemory:'No se ha medido RAM/VRAM pico.'};G.lastCapabilities=report;return report;
}
G.GenieCapabilityProbe={probe,recommendProfile,idbTest,withTimeout,workerTest};
})();
