/* v7.2.1: actual capability checks. No weights, no attempt and no grade writes. */
(()=>{'use strict';const G=window.GeniusMath;
const labels={origin:'HTTPS / localhost',secureContext:'Contexto seguro',webgpu:'WebGPU',adapter:'Adaptador GPU',worker:'Worker de inferencia',indexedDB:'IndexedDB · escribir / leer / borrar',storage:'Espacio del navegador',persistence:'Persistencia de almacenamiento',online:'Conectividad',iframe:'Entorno / iframe',policy:'Políticas detectables',runtime:'Runtime JavaScript',modelConfig:'Servidor y configuración del modelo'};
const now=()=>performance.now();
function withTimeout(promise,ms,label,signal){return new Promise((resolve,reject)=>{let done=false;const end=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);fn(v)};const abort=()=>end(reject,G.util.abortError());const timer=setTimeout(()=>end(reject,Object.assign(Error(label+' no respondió a tiempo.'),{code:'TIMEOUT'})),ms);if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});Promise.resolve(promise).then(v=>end(resolve,v),e=>end(reject,e))})}
function idbTest(idb,{timeoutMs=5000,signal}={}){return new Promise((resolve,reject)=>{let db=null,done=false,request=null;const name=G.util.id('GeniusCapabilityProbe');
 const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);try{db?.close();idb?.deleteDatabase(name)}catch(_){}error?reject(error):resolve(value)};
 const abort=()=>finish(G.util.abortError());const timer=setTimeout(()=>finish(Error('IndexedDB no respondió (bloqueo o espera de apertura).')),timeoutMs);
 if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});try{if(!idb)throw Error('IndexedDB no está disponible.');request=idb.open(name,1);request.onupgradeneeded=()=>request.result.createObjectStore('probe');request.onerror=()=>finish(request.error||Error('No se pudo abrir IndexedDB.'));request.onblocked=()=>finish(Error('IndexedDB está bloqueado por otra conexión o una política.'));request.onsuccess=()=>{db=request.result;if(done){db.close();idb.deleteDatabase(name);return}try{const tx=db.transaction('probe','readwrite'),store=tx.objectStore('probe');store.put('real-probe','key');const read=store.get('key');let matched=false,deleted=false;read.onsuccess=()=>{matched=read.result==='real-probe';store.delete('key');const after=store.get('key');after.onsuccess=()=>{deleted=after.result===undefined}};tx.onerror=()=>finish(tx.error||Error('IndexedDB rechazó la transacción.'));tx.onabort=()=>finish(tx.error||Error('IndexedDB abortó la transacción.'));tx.oncomplete=()=>matched&&deleted?finish(null,{open:true,write:true,read:true,delete:true}):finish(Error('La lectura/borrado de prueba no coincide.'))}catch(e){finish(e)}}}catch(e){finish(e)}})}
function workerTest(url,{timeoutMs=8000,signal}={}){return new Promise((resolve,reject)=>{let worker=null,done=false;const end=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);worker?.terminate();fn(v)};const abort=()=>end(reject,G.util.abortError());const timer=setTimeout(()=>end(reject,Error('El Worker no confirmó su inicio. Revisa worker-src, la ruta y el tipo MIME.')),timeoutMs);if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});try{worker=new Worker(url,{type:'module',name:'GeniusCapabilityProbe'});worker.onmessage=e=>{if(e.data?.probeVersion==='7.2.1')end(resolve,e.data)};worker.onerror=e=>end(reject,Error(e.message||'Creación/carga del Worker bloqueada.'));worker.postMessage({type:'probe'})}catch(e){end(reject,e)}})}
function recommendProfile(cap){const m=cap.deviceMemoryGB,lim=cap.adapter?.limits||{},disk=cap.storage?.availableBytes;let profile='light',rule='unknown_or_conservative';const enough=bytes=>typeof disk==='number'&&disk>=bytes;
 if(m>=16&&lim.maxBufferSize>=1073741824&&lim.maxStorageBufferBindingSize>=268435456&&enough(7e9)){profile='advanced';rule='ram_hint_16_buffer_1GiB_storage_7GB'}
 else if(m>=8&&lim.maxBufferSize>=268435456&&lim.maxStorageBufferBindingSize>=134217728&&enough(3e9)){profile='standard';rule='ram_hint_8_buffer_256MiB_storage_3GB'}
 return{profile,rule,kind:'conservative_hardware_trial_not_quality_selection',recommendedDefault:null,inputs:{deviceMemoryGB:m??null,limits:lim,availableBytes:disk??null},reason:profile==='light'?'Prueba conservadora: memoria GPU libre no medible o recursos limitados. Puedes elegir otro perfil.':'Los datos disponibles permiten probar un perfil mayor; no garantizan memoria GPU libre ni calidad pedagógica.',policy:'PROFILE_POLICY.md'};}
async function probe({signal,onCheck,worker=true}={}){const start=now(),n=navigator,checks=[];const report={version:G.config.version,kind:'actual_browser_capability_probe',executed:true,at:new Date().toISOString(),environment:{protocol:location.protocol,origin:location.origin,secureContext:!!globalThis.isSecureContext,topEqualsSelf:window.top===window.self,userAgent:n.userAgent,platform:n.userAgentData?.platform||n.platform||null},deviceMemoryGB:typeof n.deviceMemory==='number'?n.deviceMemory:null,adapter:null,storage:null,checks};
 const add=(id,status,message,{required=false,value=null,code=id.toUpperCase(),impact='',remedy=''}={})=>{const x={id,label:labels[id]||id,status,message,required,code,value,impact,remedy,continueWithoutAI:true};checks.push(x);onCheck?.(x,report);return x};
 const loopback=['localhost','127.0.0.1','[::1]'].includes(location.hostname);const valid=location.protocol==='https:'||(location.protocol==='http:'&&loopback);
 add('origin',valid?'pass':'fail',valid?'Página servida por HTTPS o localhost.':location.protocol==='file:'?'Esta página se abrió como archivo local (file://).':'El origen no es HTTPS ni localhost.',{required:true,code:location.protocol==='file:'?'FILE_PROTOCOL':'UNSUPPORTED_ORIGIN',impact:'El runtime modular y el almacenamiento del modelo necesitan un origen web válido.',remedy:'Usa un origen web válido: HTTPS (por ejemplo GitHub Pages o Brightspace) o localhost. Para prueba local, extrae el ZIP y abre http://localhost:8000/ mediante serve_local.py; no abras index.html con doble clic.'});
 add('secureContext',globalThis.isSecureContext?'pass':'fail',globalThis.isSecureContext?'El navegador reconoce un contexto seguro.':'El navegador no reconoce un contexto seguro.',{required:true,remedy:'Usa HTTPS o localhost; el administrador debe comprobar también el contexto del iframe.'});
 add('webgpu',n.gpu?'pass':'fail',n.gpu?'La API WebGPU está expuesta.':'Este navegador no expone navigator.gpu.',{required:true,code:'WEBGPU_UNAVAILABLE',impact:'No se puede ejecutar este proveedor local sin WebGPU.',remedy:'Prueba un navegador actualizado con aceleración gráfica habilitada. Consulta el diagnóstico GPU del navegador; también puedes jugar con la Guía compatible.'});
 try{if(!n.gpu)throw Error('WebGPU no está disponible.');const a=await withTimeout(n.gpu.requestAdapter(),7000,'Adaptador GPU',signal);if(!a)throw Error('requestAdapter() devolvió null.');const keys=['maxBufferSize','maxStorageBufferBindingSize','maxComputeWorkgroupStorageSize','maxComputeInvocationsPerWorkgroup','maxComputeWorkgroupSizeX','maxStorageBuffersPerShaderStage'];report.adapter={obtained:true,f16:a.features.has('shader-f16'),limits:Object.fromEntries(keys.map(k=>[k,a.limits[k]??null])),info:a.info?{vendor:a.info.vendor||null,architecture:a.info.architecture||null,isFallbackAdapter:a.info.isFallbackAdapter??null}:null};add('adapter','pass','Adaptador obtenido; se comprobará también en el Worker.',{required:true,value:report.adapter})}catch(e){if(e.name==='AbortError')throw e;add('adapter','fail','No se obtuvo un adaptador: '+e.message,{required:true,code:'ADAPTER_UNAVAILABLE',remedy:'Revisa aceleración gráfica, controladores y políticas del navegador. No hay información suficiente para atribuirlo a una GPU concreta.'})}
 try{if(!worker)throw Error('Prueba de Worker omitida explícitamente.');const w=await workerTest(G.config.localModel.probeWorker,{signal});report.worker=w;if(!w.adapterObtained)throw Error(w.error||'El Worker inició, pero no obtuvo adaptador WebGPU.');add('worker','pass','Worker modular y adaptador en el Worker confirmados por ida y vuelta.',{required:true,value:w})}catch(e){if(e.name==='AbortError')throw e;add('worker',worker?'fail':'unknown',e.message,{required:true,code:'WORKER_UNAVAILABLE',remedy:'Revisa worker-src/CSP, rutas y archivos .js servidos correctamente. El iframe debe permitir cargar el Worker de este origen.'})}
 try{const val=await idbTest(n?globalThis.indexedDB:null,{signal});add('indexedDB','pass','Apertura, escritura, lectura y borrado temporal comprobados.',{required:true,value:val})}catch(e){if(e.name==='AbortError')throw e;add('indexedDB','fail',e.message,{required:true,code:'INDEXEDDB_BLOCKED',impact:'No se puede garantizar almacenamiento de pesos y conversación.',remedy:'Permite almacenamiento para este origen. Revisa modo privado y restricciones del iframe. No borres el historial de Poker.'})}
 try{if(!n.storage?.estimate)throw Error('StorageManager.estimate no disponible.');const x=await withTimeout(n.storage.estimate(),4000,'Cuota',signal);report.storage={quota:x.quota??null,usage:x.usage??null,availableBytes:Number.isFinite(x.quota)&&Number.isFinite(x.usage)?Math.max(0,x.quota-x.usage):null};add('storage','pass','Cuota estimada del origen, no memoria RAM ni VRAM.',{value:report.storage})}catch(e){if(e.name==='AbortError')throw e;add('storage','unknown',e.message,{code:'STORAGE_ESTIMATE_UNAVAILABLE',remedy:'La carga seguirá sujeta al espacio que realmente conceda el navegador.'})}
 try{if(!n.storage?.persisted)throw Error('API de persistencia no disponible.');const value=await withTimeout(n.storage.persisted(),3000,'Persistencia',signal);add('persistence',value?'pass':'warning',value?'El origen tiene almacenamiento persistente.':'Caché no persistente: el navegador puede desalojarla.',{value,remedy:'El botón Conservar caché solicita persistencia; el navegador decide si la concede.'})}catch(e){if(e.name==='AbortError')throw e;add('persistence','unknown',e.message)}
 add('online',n.onLine===false?'warning':'pass',n.onLine===false?'El navegador declara estar sin conexión.':'El navegador declara conexión; esto no prueba acceso a los servidores.',{value:n.onLine??null,code:'OFFLINE',remedy:'Para la primera descarga necesitas red. Una caché parcial no garantiza funcionamiento sin conexión.'});
 let parentOrigin=null;try{parentOrigin=window.parent.location.origin}catch(_){parentOrigin='cross-origin: no accesible'}report.environment.parentOrigin=parentOrigin;
 add('iframe',window.top===window.self?'pass':'warning',window.top===window.self?'Pestaña independiente.':'Actividad en iframe: no se intentará salir del reproductor.',{value:{...report.environment},remedy:'Compara el diagnóstico en una pestaña de prueba y en el reproductor LMS. El administrador debe revisar políticas y almacenamiento de terceros.'});
 let policies={inspectionAvailable:false,webgpuPolicy:null,sandbox:null};try{const p=document.permissionsPolicy||document.featurePolicy;const known=p?.features?.();if(known){policies.inspectionAvailable=true;if(known.includes('webgpu'))policies.webgpuPolicy=p.allowsFeature('webgpu')}policies.sandbox=window.frameElement?.getAttribute('sandbox')??null}catch(_){}report.policies=policies;
 add('policy',policies.webgpuPolicy===false?'fail':'unknown',policies.webgpuPolicy===false?'Una política detectable impide WebGPU.':'CSP completa y políticas del padre no siempre son legibles; se registrarán los bloqueos observados.',{value:policies,required:policies.webgpuPolicy===false,remedy:'Revisa consola, CSP connect-src/script-src/worker-src, WebAssembly y permisos efectivos; no se presupone una directiva WebGPU universal.'});
 add('runtime','unknown','Se importará y comprobará después de autorizar la preparación; aún no se han descargado pesos.',{code:'RUNTIME_PENDING'});add('modelConfig','unknown','El acceso a configuración, registro y servidor de pesos se comprobará durante la preparación.',{code:'MODEL_RESOURCES_PENDING'});
 report.supported=checks.filter(x=>x.required).every(x=>x.status==='pass');report.recommendation=recommendProfile(report);report.durationMs=now()-start;report.measurementUnavailableReason={freeVRAM:'WebGPU no expone una medida portátil de VRAM libre.',peakMemory:'No se ha medido RAM/VRAM pico.'};G.lastCapabilities=report;return report;
}
G.GenieCapabilityProbe={probe,recommendProfile,idbTest,withTimeout,workerTest};
})();
