/* Integrated activation dialog. Opening/closing never creates a Poker attempt. */
(()=>{'use strict';const G=window.GeniusMath,$=id=>document.getElementById(id);let report=null,probeController=null,probing=null,running=false,opened=false,lastFocus=null,inertState=[],manualProfile=false;
const node=(tag,attrs={},text)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e};
const root=node('div',{id:'geniusCapabilityOverlay',class:'genius-cap-overlay',hidden:''});
root.innerHTML=`<section class="genius-cap-dialog" role="dialog" aria-modal="true" aria-labelledby="geniusCapTitle" aria-describedby="geniusCapIntro" tabindex="-1">
<header class="genius-cap-header"><div><p class="genius-eyebrow">POKER EDO · GENIUS MATH</p><h2 id="geniusCapTitle">Prepara tu tutor</h2></div><button id="geniusCapClose" class="genius-icon-btn" aria-label="Cerrar panel de compatibilidad">×</button></header>
<div class="genius-cap-scroll"><p id="geniusCapIntro">Comprueba este equipo antes de descargar el modelo. La preparación desde el menú no consume la hora de juego.</p>
<div id="geniusCapabilitySummary" class="genius-cap-summary" role="status" aria-live="polite">Comprobando el dispositivo…</div>
<div class="genius-cap-columns"><section><h3>Comprobación del dispositivo</h3><ul id="geniusCapabilityChecks" class="genius-checks" aria-label="Pruebas de compatibilidad"></ul></section>
<section class="genius-model-card"><h3>Modelo local</h3><label for="geniusCapProfile">Perfil de prueba</label><select id="geniusCapProfile"></select><p id="geniusProfileReason" class="genius-small"></p><dl><dt>Modelo</dt><dd id="geniusModelName"></dd><dt>Primera descarga</dt><dd id="geniusModelSize"></dd><dt>Memoria GPU de referencia</dt><dd id="geniusModelMemory"></dd></dl><p class="genius-small">Las cifras son estimaciones, no medidas de tu GPU. Ningún candidato está certificado como mejor tutor.</p><p class="genius-small">Los pesos se almacenan en este origen. Una recarga debe volver a iniciar el motor; la caché puede evitar descargar pesos, pero el navegador puede desalojarla.</p><button id="geniusPersist" class="genius-secondary">Solicitar conservación de caché</button><p id="geniusPersistResult" class="genius-small" role="status"></p></section></div>
<section id="geniusLoadProgress" class="genius-load-progress" hidden><strong id="geniusLoadStage">Preparando…</strong><progress id="geniusRealProgress" max="1"></progress><p id="geniusProgressDetail" class="genius-small" role="status"></p></section>
<details class="genius-technical"><summary>Detalle técnico y privacidad</summary><p>No se envían conversaciones para la inferencia local. Los servidores de descarga reciben las solicitudes de recursos. Este diagnóstico no contiene tu nombre, código, nota ni conversación. La URL se limita al origen.</p><p id="geniusRuntimeOrigin"></p><pre id="geniusCapabilityDetail"></pre><button id="geniusExportDiagnostic" class="genius-secondary">Guardar diagnóstico JSON</button></details></div>
<footer class="genius-cap-footer"><div class="genius-cap-actions"><button id="geniusPrepare" class="genius-primary" disabled>PREPARAR GENIUS</button><button id="geniusRetry" class="genius-secondary">VOLVER A COMPROBAR</button><button id="geniusCancelPreparation" class="genius-secondary" hidden>CANCELAR PREPARACIÓN</button><button id="geniusDismiss" class="genius-secondary">CONTINUAR SIN IA LOCAL</button></div><small>Cerrar este panel no inicia la partida ni modifica tu nota.</small></footer></section>`;
document.body.append(root);
const select=$('geniusCapProfile');for(const[k,v]of Object.entries(G.config.profiles))select.append(node('option',{value:k},v.label));
$('geniusRuntimeOrigin').textContent=G.config.localModel.runtimeBundled?'Runtime JavaScript incluido en el paquete; pesos y WASM siguen externos.':'Runtime JavaScript externo: '+G.config.localModel.runtimeURL+'. Pesos/configuración en Hugging Face y biblioteca WASM según el registro de WebLLM.';
function updateDetails(){const d=G.RuntimeDiagnostics.snapshot();if(report)d.capabilities=report;$('geniusCapabilityDetail').textContent=JSON.stringify(d,null,2)}
function modelInfo(){const c=G.config.profiles[select.value];if(!c)return;const f16=report?.adapter?.f16!==false&&report?.worker?.f16!==false;$('geniusModelName').textContent=f16?c.model:c.f32;$('geniusModelSize').textContent=c.downloadEstimate+(f16?'':' · la variante f32 puede necesitar más espacio');$('geniusModelMemory').textContent=((f16?c.vramMB:c.vramF32MB)/1000).toFixed(2)+' GB (registro upstream; no VRAM medida)';$('geniusProfileReason').textContent=manualProfile?'Selección manual. La carga real decide si este perfil funciona en tu equipo.':report?.recommendation?.reason||'La recomendación se calculará con los datos disponibles; por ahora se muestra el candidato ligero.';if($('genieProfile'))$('genieProfile').value=select.value}
function renderChecks(){const ul=$('geniusCapabilityChecks');ul.replaceChildren();for(const check of report?.checks||[]){const li=node('li',{class:'genius-check '+check.status});li.append(node('span',{'aria-hidden':'true',class:'genius-check-icon'},check.status==='pass'?'✓':check.status==='fail'?'!':check.status==='warning'?'△':'—'));const b=node('div');b.append(node('strong',{},check.label),node('small',{},check.message));li.append(b);ul.append(li)}}
function buttons(){const busy=running||!!probing,p=G.ModelProvider.local();$('geniusPrepare').disabled=busy||!report?.supported;$('geniusRetry').disabled=busy;select.disabled=busy;$('geniusCancelPreparation').hidden=!busy;$('geniusPersist').disabled=busy;$('geniusDismiss').textContent=p.ready&&p.liveInference?'VOLVER AL JUEGO':'CONTINUAR SIN IA LOCAL';}
function summarize(diagnostic){const p=G.ModelProvider.local(),box=$('geniusCapabilitySummary');box.className='genius-cap-summary';if(diagnostic){box.classList.add('warn');box.replaceChildren(node('strong',{},diagnostic.cause),node('p',{},diagnostic.impact||'La IA local no se activó.'),node('p',{},diagnostic.remedy||'Puedes continuar sin IA.'));}
 else if(p.ready&&p.liveInference){box.classList.add('ok');box.textContent='Genius listo · el modelo completó una generación interna real. Puedes volver al juego.'}
 else if(report){const first=report.checks.find(x=>x.required&&x.status!=='pass');if(first){summarize({cause:first.message,impact:first.impact||'Genius local no puede iniciarse con esta comprobación.',remedy:first.remedy});return}else{box.classList.add('ok');box.textContent='Comprobaciones locales superadas. Falta cargar los recursos y superar una generación real; eso ocurrirá al pulsar Preparar Genius.'}}
 const label=$('preloadGeniusStatus');if(label)label.textContent=p.ready&&p.liveInference?'Genius listo para esta sesión':diagnostic?diagnostic.cause:report?.supported?'Equipo comprobado · abre para preparar el modelo':report?.checks.find(x=>x.required&&x.status!=='pass')?.message||'Comprobando este equipo…';updateDetails();buttons();}
async function checkDevice(){if(probing||running)return probing;probeController=new AbortController();const ctl=probeController;report={checks:[]};$('geniusCapabilitySummary').textContent='Comprobando el dispositivo…';
 probing=G.GenieCapabilityProbe.probe({signal:ctl.signal,onCheck:(check,partial)=>{report=partial;renderChecks()}});buttons();try{report=await probing;if(!manualProfile)select.value=report.recommendation.profile;modelInfo();renderChecks();summarize()}catch(e){if(e.name!=='AbortError')summarize(G.RuntimeDiagnostics.classify(e,'capabilities'));else{$('geniusCapabilitySummary').textContent='Comprobación cancelada. Puedes volver a comprobar el equipo.'}}finally{probing=null;probeController=null;buttons()}return report}
function focusables(){return [...root.querySelectorAll('button,select,a[href],summary,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled&&!x.closest('[hidden]')&&x.getClientRects().length)}
function open(options={}){if(options.profile){select.value=options.profile;manualProfile=true}if(!opened){lastFocus=options.returnFocus||document.activeElement;inertState=[...document.body.children].filter(x=>x!==root&&x.tagName!=='SCRIPT').map(x=>({element:x,inert:x.inert}));for(const x of inertState)x.element.inert=true;root.hidden=false;opened=true;$('geniusCapClose').focus();}modelInfo();buttons();if(!report&&!probing)void checkDevice();else summarize(G.ModelProvider.local().diagnostic)}
function close(){if(probing)probeController?.abort();if(running)G.ModelProvider.local().cancel();root.hidden=true;opened=false;for(const x of inertState)x.element.inert=x.inert;inertState=[];if(lastFocus?.isConnected)lastFocus.focus()}
async function prepare(){if(running||probing||!report?.supported)return;running=true;$('geniusLoadProgress').hidden=false;$('geniusRealProgress').removeAttribute('value');$('geniusCapabilitySummary').textContent='Preparando Genius… Puedes cancelar o continuar sin IA.';buttons();
 try{await G.ModelProvider.activateLocal(select.value);summarize();G.TutorPanel?.refresh();}catch(e){summarize(e.diagnostic||G.RuntimeDiagnostics.classify(e,e.stage));}finally{running=false;buttons();updateDetails()}}
$('preloadGeniusBtn')?.addEventListener('click',()=>open());$('geniusCapClose').addEventListener('click',close);$('geniusDismiss').addEventListener('click',close);$('geniusRetry').addEventListener('click',()=>{manualProfile=false;G.ModelProvider.local().diagnostic=null;void checkDevice()});$('geniusPrepare').addEventListener('click',prepare);$('geniusCancelPreparation').addEventListener('click',()=>{probeController?.abort();G.ModelProvider.local().cancel();$('geniusLoadStage').textContent='Cancelando…'});select.addEventListener('change',()=>{manualProfile=true;modelInfo()});$('geniusExportDiagnostic').addEventListener('click',()=>G.RuntimeDiagnostics.download({...G.RuntimeDiagnostics.snapshot(),capabilities:report}));
$('geniusPersist').addEventListener('click',async()=>{try{if(!navigator.storage?.persist)throw Error('Este navegador no expone la solicitud de persistencia.');const granted=await navigator.storage.persist();$('geniusPersistResult').textContent=granted?'Persistencia concedida. Aun así, conserva tus informes.':'El navegador no concedió persistencia. La caché puede seguir siendo temporal.'}catch(e){$('geniusPersistResult').textContent=e.message}});
root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close()}else if(e.key==='Tab'){const items=focusables();if(!items.length){e.preventDefault();return}const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
window.addEventListener('genius:capability-check',e=>{if(!running)return;report=e.detail.report;renderChecks()});
window.addEventListener('genius:capability-check',e=>{if(running){report=e.detail.report;renderChecks();updateDetails()}});
window.addEventListener('genius:runtime-check',e=>{if(!report)return;const i=report.checks.findIndex(x=>x.id===e.detail.id);if(i<0)report.checks.push(e.detail);else report.checks[i]=e.detail;renderChecks();updateDetails()});
const stageNames={runtime:'Cargando runtime',model_config:'Comprobando servidor del modelo',weights:'Cargando pesos',compiling:'Compilando recursos GPU',initializing:'Inicializando modelo',warming:'Calentando · generación real de prueba',ready:'Genius listo',generation:'Genius está pensando…'};
window.addEventListener('genius:model-state',e=>{const d=e.detail;if(['loading','warming'].includes(d.status)&&running){$('geniusLoadProgress').hidden=false;$('geniusLoadStage').textContent=stageNames[d.stage]||'Preparando Genius';if(typeof d.progress==='number'&&d.progress>=0&&d.progress<=1){$('geniusRealProgress').value=d.progress;$('geniusProgressDetail').textContent=Math.round(d.progress*100)+' % comunicado por el runtime (no porcentaje de bytes). '+(d.text||'')}else{$('geniusRealProgress').removeAttribute('value');$('geniusProgressDetail').textContent=(d.text||'Progreso por etapas; no hay porcentaje disponible.')}}
 if(['ready','error','cancelled'].includes(d.status)){if(d.status==='ready')$('geniusLoadStage').textContent='Genius listo';summarize(d.diagnostic||null)}buttons()});
G.PreloadPanel={open,close,checkDevice,prepare,getReport:()=>report};modelInfo();setTimeout(()=>{void checkDevice()},250);
})();
