(()=>{'use strict';const G=window.GeniusMath;const violations=[];const origins=s=>{try{return new URL(s,location.href).origin}catch(_){return String(s||'').slice(0,80)}};
window.addEventListener('securitypolicyviolation',e=>{violations.push({at:Date.now(),directive:e.effectiveDirective||e.violatedDirective,blockedOrigin:origins(e.blockedURI),disposition:e.disposition});if(violations.length>30)violations.shift()});
function classify(error,stage='preparation'){
 const raw=String(error?.message||error||'Sin detalle').slice(0,700),name=error?.name||'Error';let code=error?.code||'RUNTIME_ERROR',cause='Falló la etapa '+stage+'. '+raw,remedy='Reintenta solo si el equipo permanece estable o continúa con la Guía compatible. El detalle no identifica por sí solo una causa única.',impact='La IA local no se declara activa. Poker y la nota siguen independientes.';
 const csp=violations.filter(x=>x.disposition==='enforce'&&Date.now()-x.at<15000);
 if(name==='AbortError'){code='CANCELLED';cause='Operación cancelada.';remedy='Tu partida y tus informes se conservan. Puedes continuar sin IA o volver a preparar Genius.'}
 else if(error?.diagnostic)return error.diagnostic;
 else if(code==='F16_REQUIRED_SAFE_MODE'||/shader-f16|modo seguro requiere/i.test(raw)){code='F16_REQUIRED_SAFE_MODE';cause='El modo local seguro requiere shader-f16 en la página y en el Worker.';remedy='No se cargará automáticamente una variante f32 de mayor consumo. Continúa con la Guía compatible en este equipo.'}
 else if(code==='PROTOCOL_TRUNCATED'){cause='El modelo alcanzó el límite de salida antes de cerrar el JSON de respuesta.';remedy='Se usa una ayuda segura local sin lanzar una segunda inferencia. Si se repite, continúa con la guía y exporta el diagnóstico.'}
 else if(code==='EMPTY_GENERATION'){cause='El modelo no produjo una respuesta utilizable.';remedy='Se usa una ayuda segura sin una segunda inferencia. Si el runtime pierde estabilidad, vuelve a preparar Genius o continúa sin IA.'}
 else if(code==='INPUT_TOO_LARGE'){cause='El contexto conversacional superó el límite conservador de esta versión.';remedy='La conversación se compactará en los siguientes turnos; usa una consulta breve o continúa con la guía. No se lanza una segunda inferencia.'}
 else if(code==='WORKER_CRASH'||code==='WORKER_MESSAGE_ERROR'){cause='El Worker de inferencia se cerró o dejó de comunicarse.';remedy='La IA local se detiene para evitar cargas huérfanas. No pruebes modelos mayores; recarga y usa la Guía compatible si el equipo mostró inestabilidad.'}
 else if(csp.length&&/fetch|import|module|worker|wasm|content security|csp/i.test(raw)){code='CSP_BLOCK';cause='Se observó un bloqueo de política de contenido: '+csp.map(x=>x.directive).join(', ')+'. Etapa: '+stage;remedy='El administrador debe revisar las directivas registradas. No se puede modificar la política del LMS desde el SCORM.'}
 else if(/QuotaExceeded|quota|indexeddb|IDBDatabase|storage/i.test(name+' '+raw)){code='STORAGE_FAILURE';cause='El almacenamiento del modelo falló. '+raw;remedy='Revisa cuota y permisos de almacenamiento del origen. No borres el historial de informes; limpia únicamente la caché del modelo si decides hacerlo.'}
 else if(/out of memory|DeviceLost|device lost|GPU device|memory allocation|GPUValidationError|GPUInternalError/i.test(raw)||/GPU_RESOURCE|GPU_DEVICE|DEVICE_LOST/.test(code)){code='GPU_RESOURCE_FAILURE';cause='El runtime notificó pérdida del dispositivo o recursos GPU insuficientes. '+raw;remedy='Detén la IA local en este equipo. No pruebes 1.7B/4B. Si hubo pantalla negra o reinicio, usa la Guía compatible hasta revisar el controlador/GPU.'}
 else if(/TIMEOUT|timeout|tiempo|límite de espera/i.test(code+' '+raw)){code='OPERATION_TIMEOUT';remedy='La operación se detuvo para evitar una tarea abandonada. Si el equipo ya mostró inestabilidad, continúa sin IA local en vez de repetir cargas largas.'}
 else if(/fetch|import|module|network|HTTP|offline/i.test(raw)&&globalThis.navigator?.onLine===false){code='OFFLINE_RESOURCE_ACCESS';cause='El navegador declara estar sin conexión y falló el acceso al recurso en '+stage+'.';remedy='Recupera la conexión para la primera descarga. Puedes usar la guía sin IA; una caché parcial no garantiza ejecución sin red.'}
 else if(/fetch|import|module|network|HTTP|offline/i.test(raw)){code=stage==='runtime'?'RUNTIME_IMPORT_FAILED':'RESOURCE_ACCESS_FAILED';cause='No se pudo acceder al recurso en la etapa '+stage+'. '+raw;remedy='Comprueba red, CORS, script-src/connect-src y los orígenes mostrados. Un TypeError de fetch no permite distinguir DNS, CORS y CSP sin evidencia adicional.'}
 else if(/ModelNotLoaded|not loaded|no model|pipeline.*not/i.test(raw)){code='MODEL_NOT_LOADED';cause='El runtime perdió el modelo cargado. '+raw;remedy='No se afirmará que Genius está listo sin una nueva generación de comprobación. Si el equipo fue inestable, usa la guía sin IA.'}
 else if(/schema|grammar|token|JSON|smoke/i.test(raw)||/SMOKE|PROTOCOL|SCHEMA/.test(code)){code=code==='RUNTIME_ERROR'?'MODEL_PROTOCOL_FAILED':code;cause='El modelo/runtime no superó el protocolo de respuesta comprobado. '+raw;remedy='No se ejecutará una segunda generación automática; conserva el diagnóstico y continúa con la ayuda segura.'}
 return{code,cause,impact,remedy,stage,continueWithoutAI:true,observedCSP:csp};
}
const dbName='GeniusRuntimeEvidenceV722';
async function save(value){try{return await new Promise((resolve)=>{let db;const timer=setTimeout(()=>{db?.close();resolve(false)},4000);const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('runs',{keyPath:'id'});r.onerror=r.onblocked=()=>{clearTimeout(timer);resolve(false)};r.onsuccess=()=>{db=r.result;const tx=db.transaction('runs','readwrite');tx.objectStore('runs').put(value);tx.oncomplete=()=>{clearTimeout(timer);db.close();resolve(true)};tx.onerror=()=>{clearTimeout(timer);db.close();resolve(false)}}})}catch(_){return false}}
async function all(){try{return await new Promise(resolve=>{let db;const timer=setTimeout(()=>{db?.close();resolve([])},4000);const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('runs',{keyPath:'id'});r.onerror=r.onblocked=()=>{clearTimeout(timer);resolve([])};r.onsuccess=()=>{db=r.result;const tx=db.transaction('runs','readonly'),q=tx.objectStore('runs').getAll();q.onsuccess=()=>{clearTimeout(timer);db.close();resolve(q.result||[])};q.onerror=()=>{clearTimeout(timer);db.close();resolve([])}}})}catch(_){return []}}
function download(data,name='GENIUS_DEVICE_DIAGNOSTIC_V722.json'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
G.RuntimeDiagnostics={classify,save,all,download,violations,pageId:G.util.id('page'),snapshot(){const p=G.ModelProvider?.local();return{version:G.config.version,capabilities:G.lastCapabilities||null,providerKind:p?.providerKind||null,liveInference:p?.liveInference===true,modelId:p?.model||null,runtimeBundled:G.config.localModel.runtimeBundled,diagnostic:p?.diagnostic||null,load:p?.lastLoad||null,runtimeChecks:p?.runtimeChecks||[],observedCSP:violations.slice()}}};
})();
