(()=>{'use strict';const G=window.GeniusMath,$=id=>document.getElementById(id);let hooks={},busy=false,lastFocus=null,bound=false,hiddenDisposeTimer=null;
const text=(id,value)=>{const el=$(id);if(el)el.textContent=value};
function status(message){text('genieStatus',message)}
function isReady(p){return !!p?.generative&&!!p.ready&&(p.kind!=='local'||p.liveInference===true)}
function populateProfiles(){const sel=$('genieProfile');if(!sel)return;const previous=sel.value;sel.replaceChildren();for(const[k,v]of Object.entries(G.config.profiles||{})){const opt=document.createElement('option');opt.value=k;opt.textContent=v.label||k;sel.append(opt)}const preferred=G.config.profiles?.[previous]?previous:(G.config.profiles?.[G.config.localModel.profile]?G.config.localModel.profile:Object.keys(G.config.profiles||{})[0]);if(preferred)sel.value=preferred;sel.disabled=!sel.options.length;if($('genieInput'))$('genieInput').maxLength=G.config.maxMessageChars||1000}
function refresh(){const provider=G.ModelProvider.current(),local=G.ModelProvider.local(),ready=isReady(provider),localBusy=local.initializing||['probing','loading','warming','generating','cancelling'].includes(local.status),blocked=busy||localBusy;
 text('genieHelpBadge',provider.kind==='guided'?'Guía compatible · sin IA':ready?(provider.kind==='cloud'?'IA conectada':'IA local · modo seguro'):'IA no activada');
 $('genieForm')?.classList.toggle('hidden',provider.kind==='guided');if($('genieSendBtn'))$('genieSendBtn').disabled=blocked||!ready;if($('genieInput'))$('genieInput').disabled=blocked||!ready;if($('genieCancelBtn'))$('genieCancelBtn').classList.toggle('hidden',!blocked);
 if($('genieLoadBtn'))$('genieLoadBtn').disabled=blocked;if($('genieProfile'))$('genieProfile').disabled=blocked||!$('genieProfile').options.length;
 $('genieCloudBtn')?.classList.toggle('hidden',!G.config.cloud.enabled);if($('genieCloudBtn'))$('genieCloudBtn').disabled=blocked;
 if($('genieModeDetails'))$('genieModeDetails').open=!ready&&provider.kind!=='guided';
 text('genieEngineNote',provider.kind==='guided'?'Referencia verificada de fórmulas. No hay generación de respuestas.':ready?'Modelo ligero local activo en modo de estabilidad. Puede equivocarse; el Evaluator del juego verifica la corrección académica.':'El chat necesita activar el modelo ligero seguro. La Guía compatible funciona sin IA.');
}
function setBusy(value){busy=!!value;refresh();$('genieChat')?.setAttribute('aria-busy',String(busy))}
function show(){lastFocus=document.activeElement;$('geniePanel')?.classList.remove('hidden');$('questionModal')?.classList.add('genius-open');refresh()}
function hide(){hooks.cancel?.();$('geniePanel')?.classList.add('hidden');$('questionModal')?.classList.remove('genius-open');if(lastFocus?.isConnected)lastFocus.focus()}
function references(question){const host=$('genieReference');if(!host)return;host.replaceChildren();const data=G.GuidedProvider.references(question);const title=document.createElement('h4');title.textContent='Guía compatible — sin IA';host.append(title);const desc=document.createElement('p');desc.textContent=data.objective;host.append(desc);for(const f of data.formulas){const box=document.createElement('div');box.className='genius-formula';const b=document.createElement('b');b.textContent=f.title;const formula=document.createElement('div');formula.textContent='\\['+f.latex+'\\]';const small=document.createElement('small');small.textContent=f.conditions||f.hypotheses||'';box.append(b,formula,small);host.append(box)}host.classList.remove('hidden');hooks.math?.(host)}
function bind(options){hooks=options||{};populateProfiles();if(bound){refresh();return}bound=true;
 $('genieCloseBtn')?.addEventListener('click',()=>hooks.close?.());
 $('genieCancelBtn')?.addEventListener('click',()=>{hooks.cancel?.();G.ModelProvider.cancel();status('Cancelando la operación. Tu progreso se conserva.');refresh()});
 $('genieLoadBtn')?.addEventListener('click',()=>{const profile=$('genieProfile')?.value||G.config.localModel.profile;G.PreloadPanel.open({profile,returnFocus:$('genieLoadBtn')});status('Comprueba el equipo y prepara el modelo ligero en modo seguro. Durante una partida ya iniciada el reloj continúa.')});
 $('genieGuideBtn')?.addEventListener('click',()=>{hooks.cancel?.();G.ModelProvider.useGuided();const q=hooks.question?.();if(q)references(q);hooks.guideUsed?.();status('Guía de fórmulas abierta. Para conversar, activa el modelo local seguro.');refresh()});
 $('genieCloudBtn')?.addEventListener('click',async()=>{if(!G.config.cloud.enabled)return;status('El proveedor remoto está desactivado en esta compilación.');});
 $('genieInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!busy&&!$('genieSendBtn')?.disabled)$('genieForm')?.requestSubmit()}});
 $('genieInput')?.addEventListener('input',()=>hooks.draft?.($('genieInput').value));
 window.addEventListener('genius:model-state',e=>{const d=e.detail;if(['probing','loading','warming'].includes(d.status)){const pct=d.progress;status((d.status==='warming'?'Comprobando una generación breve':d.status==='probing'?'Comprobando dispositivo':'Preparando Genius')+(typeof pct==='number'&&Number.isFinite(pct)?' · '+Math.round(pct*100)+' % comunicado por el runtime':'')+'. Puedes cancelar.')}else if(d.status==='generating')status('Genius está pensando…');else if(d.status==='cancelling')status('Deteniendo la generación…');else if(d.status==='generation-error')status((d.diagnostic?.cause||d.message||'La generación falló.')+' Se mostrará una ayuda segura si es posible.');else if(d.status==='error')status((d.diagnostic?.cause||d.message||'La IA local se detuvo.')+' '+(d.diagnostic?.remedy||''));else if(d.status==='cancelled')status(d.message||'Operación cancelada.');else if(d.status==='ready'&&G.ModelProvider.current()===G.ModelProvider.local()&&d.liveInference){$('genieReference')?.classList.add('hidden');if(!busy)status('Genius listo en modo seguro. Haz una consulta breve sobre el ejercicio.')}refresh()});
 $('geniePanel')?.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();hooks.close?.()}});
 document.addEventListener('visibilitychange',()=>{const local=G.ModelProvider.local();clearTimeout(hiddenDisposeTimer);hiddenDisposeTimer=null;if(document.hidden){if(local.status==='generating'){hooks.cancel?.();G.ModelProvider.cancel();status('La generación se canceló al ocultar la pestaña para reducir carga GPU. Tu progreso se conserva.')}else if(local.ready){hiddenDisposeTimer=setTimeout(()=>{if(document.hidden&&local.ready){local.dispose?.();status('Genius local se descargó de la GPU por inactividad en segundo plano. Tu progreso del juego se conserva; prepara Genius de nuevo para conversar.');refresh()}},45000)}}});
 window.addEventListener('pagehide',()=>{clearTimeout(hiddenDisposeTimer);hiddenDisposeTimer=null;const local=G.ModelProvider.local();if(local.status==='generating')G.ModelProvider.cancel();else if(local.ready)local.dispose?.();});
 refresh();
}
G.TutorPanel={bind,show,hide,refresh,status,setBusy,references,populateProfiles};})();
