/* Local human review only. Never generates scores or modifies transcripts/model claims. */
(()=>{'use strict';const $=id=>document.getElementById(id),dims={mathematicalCorrectness:'Corrección matemática',continuity:'Continuidad',intentUnderstanding:'Comprensión de intención',adaptation:'Adaptación',pedagogicalUsefulness:'Utilidad pedagógica',nonRepetition:'No repetición',disclosurePolicy:'Política de revelado',naturalness:'Naturalidad',appropriateConciseness:'Concisión apropiada',recovery:'Recuperación'};let data=null,index=0;
for(const[k,label]of Object.entries(dims)){const l=document.createElement('label');l.textContent=label;const s=document.createElement('select');s.id='score-'+k;s.add(new Option('Sin revisar',''));for(let n=0;n<=4;n++)s.add(new Option(String(n),String(n)));l.append(s);$('scores').append(l)}
function progress(){if(!data)return;const n=data.conversations.filter(c=>c.humanReview?.reviewer?.trim()&&Object.keys(dims).every(k=>Number.isInteger(c.humanReview.scores?.[k]))).length;$('count').textContent=n+' de '+data.conversations.length+' conversaciones con las diez puntuaciones registradas. Esto no certifica la exactitud de la revisión.'}
function show(){const c=data.conversations[index];$('conversation').value=String(index);$('context').textContent='Caso '+c.id+' · '+c.family+' · '+c.profile+' · pregunta '+c.questionId+'\n'+(c.visiblePrompt||'');$('transcript').replaceChildren();for(const t of c.turns){const d=document.createElement('div');d.className='turn';d.textContent='ESTUDIANTE: '+(t.student||'')+'\n\n'+(t.error?'ERROR DEL RUNTIME: '+t.error:'GENIUS: '+(t.assistant||''));$('transcript').append(d)}const h=c.humanReview;for(const k of Object.keys(dims))$('score-'+k).value=Number.isInteger(h?.scores?.[k])?String(h.scores[k]):'';$('notes').value=h?.notes||'';if(h?.reviewer&&!$('reviewer').value)$('reviewer').value=h.reviewer;$('transcript').scrollTop=0;progress()}
function save(){if(!data)return false;const reviewer=$('reviewer').value.trim();if(!reviewer){$('status').textContent='Escribe un identificador del revisor.';$('reviewer').focus();return false}data.conversations[index].humanReview={reviewer,reviewedAt:new Date().toISOString(),scores:Object.fromEntries(Object.keys(dims).map(k=>[k,$('score-'+k).value===''?null:Number($('score-'+k).value)])),notes:$('notes').value,source:'independent_human_review_required'};$('status').textContent='Revisión guardada en esta página. Descarga el JSON para conservarla al cerrar.';progress();return true}
$('file').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>50*1024*1024)throw Error('Máximo: 50 MB.');const x=JSON.parse(await f.text());if(!['7.2.2-safe-audited','7.2.1-rc1'].includes(x.version)||!Array.isArray(x.conversations)||!x.conversations.length||x.conversations.length>1000)throw Error('No es un resultado de conversaciones compatible con v7.2.2.');if(x.conversations.some(c=>!Array.isArray(c.turns)||c.turns.length>200||!c.id))throw Error('Transcripción no válida.');data=x;index=0;$('conversation').replaceChildren();data.conversations.forEach((c,i)=>$('conversation').add(new Option(c.id+' · '+c.family+' · '+c.profile,String(i))));for(const id of ['conversation','save','next','download'])$(id).disabled=false;$('status').textContent='Archivo cargado. Etapa '+data.stage+' · '+data.model+'. '+(data.liveInferenceExecuted===true?'El archivo declara inferencia real; contrasta su procedencia.':'El archivo NO declara inferencia real: una revisión no lo convierte en una ejecución válida.');show()}catch(e){$('status').textContent=e.message}};
$('conversation').onchange=()=>{index=Number($('conversation').value);show()};$('save').onclick=save;$('next').onclick=()=>{if(save()){index=(index+1)%data.conversations.length;show()}};$('download').onclick=()=>{if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='GENIUS_REVIEWED_'+String(data.stage||'results').replace(/[^A-Z]/g,'')+'_V722.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
})();
