import asyncio,json,copy
from pathlib import Path
from playwright.async_api import async_playwright
from browser_harness import load_page
OUT=Path(__file__).resolve().parent
EVIDENCE=OUT/'evidence';EVIDENCE.mkdir(exist_ok=True)
results=[]
def record(name,passed,**details):
 results.append({'name':name,'pass':bool(passed),**details})
 if not name.startswith('Question_transition:'):print(name, bool(passed),flush=True)
 (EVIDENCE/'browser_partial.json').write_text(json.dumps(results,ensure_ascii=False))
async def main():
 async with async_playwright() as p:
  b=await p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
  page,errors=await load_page(b,lms={'cmi.core.student_name':'Alumno Prueba','cmi.core.student_id':'P72TEST','cmi.core.lesson_mode':'normal','cmi.core.lesson_status':'not attempted'})
  record('LMS_identity',await page.locator('#studentName').input_value()=='Alumno Prueba' and await page.locator('#studentName').evaluate('(e)=>e.readOnly'))
  record('Preload_control_before_timer',await page.locator('#preloadGeniusBtn').is_visible())
  await page.locator('#preloadGeniusBtn').click();await page.wait_for_timeout(100)
  record('Preload_without_GPU_does_not_start_attempt',await page.evaluate('!__P72_TEST__.getState().gameActive') and await page.locator('#startScreen').is_visible())
  await page.locator('#geniusCapClose').click();await page.locator('#startBtn').click();await page.wait_for_timeout(150)
  record('Poker_start',await page.locator('#gameScreen').is_visible())
  base=await page.evaluate('JSON.parse(JSON.stringify(__P72_TEST__.getState()))')
  await page.locator('[data-zone]:not([disabled])').first.click()
  await page.locator('#hintBtn').click()
  record('Genius_before_answer',await page.evaluate('!__P72_TEST__.getState().currentQuestion.submitted&&__P72_TEST__.getState().currentQuestion.learning.genie.openedBeforeAnswer'))
  record('No_fake_model_when_unloaded',not await page.locator('#genieSendBtn').is_enabled())
  await page.locator('#genieGuideBtn').click();await page.wait_for_timeout(100)
  record('Explicit_nonAI_guide','sin IA' in await page.locator('#genieReference').inner_text())
  record('MathJax_guide',await page.locator('#genieReference mjx-container').count()>0 and await page.locator('#genieReference [data-mml-node="merror"]').count()==0)
  await page.locator('#genieCloseBtn').click()
  record('Closable_panel',not await page.locator('#geniePanel').is_visible())
  record('Assistance_flag_survives_close',await page.evaluate('__P72_TEST__.getState().currentQuestion.learning.genie.openedBeforeAnswer'))
  # Draft persistence before answer.
  await page.evaluate('''()=>{const c=__P72_TEST__.getState().currentQuestion,q=PokerQuestions.get(c.qId);const h=document.getElementById('answerArea');if(q.type==='mcq'){h.querySelector('input').checked=true;h.querySelector('input').dispatchEvent(new Event('change',{bubbles:true}))}else{h.querySelector('input').value='2/3';h.querySelector('input').dispatchEvent(new Event('input',{bubbles:true}))}}''')
  draft=await page.evaluate('__P72_TEST__.getState().currentQuestion.answerDraft')
  storage=await page.evaluate('__STORAGE_FIXTURE__()')
  reloaded,reload_errors=await load_page(b,storage=storage,lms=dict(await page.evaluate('__LMS_FIXTURE__.values')))
  record('Single_attempt_blocks_new_on_resume',not await reloaded.locator('#startBtn').is_enabled())
  await reloaded.locator('#continueBtn').click();await reloaded.wait_for_timeout(100)
  record('Resume_current_question',await reloaded.locator('#questionModal').is_visible())
  record('Resume_answer_draft',await reloaded.evaluate('__P72_TEST__.getState().currentQuestion.answerDraft')==draft)
  await reloaded.close()
  # Inject an openly labelled transport fixture, never a model benchmark.
  await page.evaluate('''()=>{const G=GeniusMath;window.__fixtureReply=0;G.ModelProvider.set({kind:'test_fixture_not_ai',generative:true,ready:true,cancel(){},async complete(messages,opts){if(opts.schema.properties.equivalent)return{content:JSON.stringify({equivalent:false,similarity:.1})};return{content:JSON.stringify({action:'reply',tool:'',args:{},text:'Mensaje de fixture de transporte '+(++window.__fixtureReply)+'. No corresponde a una inferencia real.',student_state:'unknown',confidence:.2,strategy:'explanation',concepts:['prueba de memoria'],formula_ids:[],errors:[],summary:'Resumen de fixture '+window.__fixtureReply,semantic_key:'fixture '+window.__fixtureReply,needs_new_strategy:false,claims_correct:false,verification_scope:'none'}),latencyMs:null}}});__P72_TEST__.openPreAnswerGenius()}''')
  for i in range(22):
   await page.locator('#genieInput').fill('Mensaje de prueba '+str(i+1))
   await page.locator('#genieSendBtn').click()
   await page.wait_for_function('(n)=>__P72_TEST__.getState().currentQuestion.learning.genie.interactions===n',arg=i+1)
  record('22_turn_transport_fixture',await page.evaluate('__P72_TEST__.getState().currentQuestion.learning.genie.interactions')==22,kind='fixture_not_model_quality')
  record('Conversation_not_in_suspend',await page.evaluate("()=>{const s=__P72_TEST__.buildSuspend();return !JSON.stringify(s).includes('Mensaje de fixture')&&!s.cq.learning.genie.turns}"))
  record('Real_IndexedDB_opaque_origin_failure_handled',await page.evaluate('!!GeniusMath.GenieMemory.lastError'))
  record('Compact_local_history_fallback',await page.evaluate("()=>{const st=__STORAGE_FIXTURE__();const x=Object.keys(st).find(k=>k.startsWith('poker_math_v712_genius_edo_corte3_500_save:'));return JSON.parse(st[x]).currentQuestion.learning.genie.turns.length<=6}"))
  # Student HTML remains literal.
  await page.evaluate("()=>{const c=__P72_TEST__.getState().currentQuestion;c.learning.genie.turns.push({role:'student',text:'<img src=x onerror=alert(1)>',at:Date.now()});__P72_TEST__.openQuestionModal()}")
  record('Chat_XSS_literal',await page.locator('#genieChat img').count()==0)
  await page.screenshot(path=str(EVIDENCE/'panel_conversation_fixture.png'))
  # Resolve an assisted question, then transfer with tutor inaccessible.
  await page.evaluate("()=>{const q=PokerQuestions.get(__P72_TEST__.getState().currentQuestion.qId),h=document.getElementById('answerArea');if(q.type==='mcq'){[...h.querySelectorAll('input')].find(e=>e.value===q.answer).checked=true}else h.querySelector('input').value=String(q.answer);__P72_TEST__.submitNormalQuestion({preventDefault(){}})}")
  record('Transition_to_transfer',await page.evaluate("__P72_TEST__.getState().currentQuestion.phase==='transfer'"))
  record('Transfer_no_tutor',not await page.locator('#geniePanel').is_visible() and not await page.locator('#hintBtn').is_enabled())
  record('Autonomy_metrics',await page.evaluate("()=>{const r=__P72_TEST__.getState().questionHistory.at(-1);return r.independent_first_attempt===false&&r.assisted_before_first_answer===true&&r.base_performance===true&&r.transfer_performance===null}"))
  transfer_state=await page.evaluate('__P72_TEST__.buildSuspend()')
  record('Suspend_under_3800',len(json.dumps(transfer_state,ensure_ascii=False,separators=(',',':')).encode())<=3800,bytes=len(json.dumps(transfer_state,ensure_ascii=False,separators=(',',':')).encode()))
  hydration=await page.evaluate('(s)=>__P72_TEST__.normalizeRestoredState(__P72_TEST__.hydrateSuspend(s))',transfer_state)
  record('Transfer_phase_survives_LMS_hydration',hydration['currentQuestion']['phase']=='transfer' and hydration['currentQuestion']['learning']['transfer']['qId']==transfer_state['cq']['learning']['transfer']['qId'])
  await page.evaluate("()=>{const s=__P72_TEST__.getState(),q=PokerQuestions.get(s.currentQuestion.learning.transfer.qId),h=document.getElementById('transferAnswerArea');if(q.type==='mcq')[...h.querySelectorAll('input')].find(e=>e.value===q.answer).checked=true;else h.querySelector('input').value=String(q.answer);__P72_TEST__.submitTransferQuestion({preventDefault(){}})}")
  record('Transfer_complete',await page.evaluate("__P72_TEST__.getState().currentQuestion.phase==='complete'"))
  record('Grade_unchanged_by_tutor_and_transfer',await page.evaluate('__P72_TEST__.getState().grade')==base['grade'])
  # Exercise the original evaluator and phase transitions across all 500 questions.
  massive=await page.evaluate('''async(base)=>{const originalTypeset=MathJax.typesetPromise;MathJax.typesetPromise=async()=>{};let rows=[];for(const q of PokerQuestions.all()){const s=JSON.parse(JSON.stringify(base));s.currentQuestion={kind:'normal',qId:q.id,target:{zone:'student',index:0,street:'preflop'},startedAt:Date.now(),submitted:false,phase:'independent',learning:{}};__P72_TEST__.setState(s);__P72_TEST__.openQuestionModal();const h=document.getElementById('answerArea');if(q.type==='mcq')[...h.querySelectorAll('input')].find(e=>e.value===q.answer).checked=true;else h.querySelector('input').value=String(q.answer);__P72_TEST__.submitNormalQuestion({preventDefault(){}});const c=s.currentQuestion;rows.push({id:q.id,correct:c.correct,phase:c.phase,tutorHidden:document.getElementById('geniePanel').classList.contains('hidden'),grade:s.grade,bytes:new TextEncoder().encode(JSON.stringify(__P72_TEST__.buildSuspend())).length});}MathJax.typesetPromise=originalTypeset;return rows}''',base)
  for r in massive:record('Question_transition:'+r['id'],r['correct'] and r['phase']=='transfer' and r['tutorHidden'] and r['grade']==base['grade'],bytes=r['bytes'],kind='canonical_reference_transition_not_independent_key_proof')
  record('500_suspend_payloads_bounded',max(r['bytes'] for r in massive)<=3800,maxBytes=max(r['bytes'] for r in massive))
  # Worst complete-bank save remains compact and decodes old sparse + new bitset forms.
  stress=await page.evaluate("""()=>{const s=__P72_TEST__.getState();s.usedQuestions=PokerQuestions.all().map(q=>q.id).concat(GeniusMath.TransferCatalog.all().map(q=>q.id));const g=s.currentQuestion.learning.genie;g.summary='Resumen '.repeat(500);g.answerChecks=2;const payload=__P72_TEST__.buildSuspend(),back=__P72_TEST__.hydrateSuspend(payload);const legacy=__P72_TEST__.hydrateSuspend({...payload,uq:'0.1.2'});return {bytes:new TextEncoder().encode(JSON.stringify(payload)).length,restored:back.usedQuestions.length,unique:new Set(back.usedQuestions).size,checks:back.currentQuestion.learning.genie.answerChecks,legacyCount:legacy.usedQuestions.length}}""")
  record('All_504_used_questions_suspend_bounded',stress['bytes']<=3800,**stress)
  record('Used_bitset_and_legacy_roundtrip',stress['restored']==504 and stress['unique']==504 and stress['legacyCount']==3)
  record('Evaluator_answer_budget_survives_hydration',stress['checks']==2)
  # Late generation result is discarded after submission.
  await page.evaluate('''(base)=>{const s=JSON.parse(JSON.stringify(base)),q=PokerQuestions.get('EDO-C3-014');s.currentQuestion={kind:'normal',qId:q.id,target:{zone:'student',index:0,street:'preflop'},startedAt:Date.now(),submitted:false,phase:'independent',learning:{}};__P72_TEST__.setState(s);__P72_TEST__.openQuestionModal();__P72_TEST__.openPreAnswerGenius();GeniusMath.ModelProvider.set({kind:'slow_fixture_not_ai',ready:true,generative:true,cancel(){},complete(){return new Promise(resolve=>window.__releaseFixture=resolve)}});GeniusMath.TutorPanel.refresh();document.getElementById('genieInput').value='prueba de cancelación';window.__pendingAsk=__P72_TEST__.askGeniusMath({preventDefault(){}});}''',base)
  await page.wait_for_function('typeof window.__releaseFixture==="function"')
  await page.evaluate('''()=>{const q=PokerQuestions.get(__P72_TEST__.getState().currentQuestion.qId);[...document.querySelectorAll('#answerArea input')].find(e=>e.value===q.answer).checked=true;__P72_TEST__.submitNormalQuestion({preventDefault(){}});window.__releaseFixture({content:'{}'});}''')
  await page.evaluate('__pendingAsk')
  record('Late_reply_dropped_on_transfer',await page.evaluate("()=>{const c=__P72_TEST__.getState().currentQuestion;return c.phase==='transfer'&&!c.learning.genie.turns.some(t=>t.role==='assistant')}"))
  # Report actually built by the existing report generator, with MathJax and fallback archiving.
  report=await page.evaluate('__P72_TEST__.buildDetailedReport()')
  record('HTML_report_generated',len(report)>1000 and 'Genius Math' in report and 'Transferencia' in report)
  record('Report_excludes_system_prompt','Devuelve SOLO un objeto JSON' not in report)
  (OUT/'SAMPLE_REPORT_TEST_FIXTURE.html').write_text(report)
  await page.evaluate("__P72_TEST__.prepareFinish('Finalización de prueba')")
  record('Safe_finish_report_first',await page.evaluate('__P72_TEST__.getState().awaitingFinalize&&__P72_TEST__.getState().reportArchived'))
  await page.evaluate('__P72_TEST__.finalizePreparedAttempt()')
  record('SCORM_final_score_sent',await page.evaluate("__LMS_FIXTURE__.log.some(x=>x[0]==='set'&&x[1]==='cmi.core.score.raw')&&__LMS_FIXTURE__.log.some(x=>x[0]==='finish')"))
  record('Single_attempt_final_lock',await page.evaluate('__P72_TEST__.studentAttemptBlocked()'))
  record('Browser_no_uncaught_errors',not errors,errors=errors)
  await page.close()
  # Preview remains non-tracked.
  preview,perrors=await load_page(b,lms={'cmi.core.student_name':'Without Tracking, Preview','cmi.core.student_id':'PREVIEW','cmi.core.lesson_mode':'browse'})
  await preview.locator('#startBtn').click()
  record('Teacher_preview_no_writes',await preview.evaluate('__LMS_FIXTURE__.log.every(x=>x[0]!=="set"&&x[0]!=="commit"&&x[0]!=="finish")'))
  record('Teacher_preview_not_locked',await preview.evaluate('!__P72_TEST__.studentAttemptBlocked()'))
  await preview.close()
  mobile,merrors=await load_page(b,viewport={'width':390,'height':844})
  await mobile.locator('#studentName').fill('Prueba móvil');await mobile.locator('#startBtn').click();await mobile.locator('#closeGuideBtn').click();await mobile.locator('[data-zone]:not([disabled])').first.click();await mobile.locator('#hintBtn').click()
  bounds=await mobile.locator('#geniePanel').bounding_box();record('Mobile_panel_fits',bounds['x']>=0 and bounds['x']+bounds['width']<=391 and bounds['height']<=844,bounds=bounds)
  await mobile.locator('#genieGuideBtn').click();await mobile.wait_for_timeout(150);await mobile.screenshot(path=str(EVIDENCE/'mobile_guide.png'));await mobile.locator('#genieCloseBtn').click();record('Mobile_panel_closes',not await mobile.locator('#geniePanel').is_visible())
  record('Mobile_no_errors',not merrors,errors=merrors)
  await b.close()
 out={'version':'7.2.2-safe-audited','environment':'Chromium offline DOM injection. localStorage and LMS are explicit fixtures. No navigation/reload on a real origin, no real model, no real Brightspace.','executed':True,'liveInference':False,'total':len(results),'passed':sum(r['pass'] for r in results),'failed':[r for r in results if not r['pass']],'results':results}
 (OUT/'BROWSER_INTEGRATION_RESULTS.json').write_text(json.dumps(out,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in out.items() if k!='results'},ensure_ascii=False,indent=2))
asyncio.run(main())
