/* Unit/API fixtures only. None of these responses is an LLM or a real GPU result. */
'use strict';const fs=require('fs'),path=require('path'),vm=require('vm'),{performance}=require('perf_hooks');const ROOT=path.resolve(__dirname,'..'),rows=[];const delay=ms=>new Promise(r=>setTimeout(r,ms));
function check(name,value,detail={}){rows.push({name,pass:!!value,kind:'unit_api_fixture_not_live_inference',...detail})}
function idbFixture(mode='normal'){
 const dbs=new Map(),calls=[];const api={calls,dbs,deleteDatabase(name){calls.push('deleteDatabase');dbs.delete(name);return {}},open(name){calls.push('open');if(mode==='throw')throw Object.assign(Error('Fixture IndexedDB blocked'),{name:'SecurityError'});const req={};if(mode==='hang')return req;
 setTimeout(()=>{if(mode==='blocked'){req.onblocked?.();return}let db=dbs.get(name),fresh=!db;if(!db){const stores=new Map();db={close(){calls.push('close')},objectStoreNames:{contains:n=>stores.has(n)},createObjectStore(n){stores.set(n,new Map());return {}},transaction(n){if(!stores.has(n))throw Error('Store missing');const data=stores.get(n),tx={},pending={n:0};let timer;const finish=()=>{clearTimeout(timer);if(!pending.n)timer=setTimeout(()=>tx.oncomplete?.(),0)};const op=fn=>{calls.push('operation');const r={};pending.n++;setTimeout(()=>{try{r.result=fn();r.onsuccess?.()}catch(e){tx.error=e;tx.onerror?.()}pending.n--;finish()},0);return r};tx.objectStore=()=>({put(v,k){calls.push('write');return op(()=>{data.set(k??v.id,structuredClone(v));return k??v.id})},add(v){return op(()=>{data.set(data.size+1,structuredClone(v));return data.size})},get(k){calls.push('read');return op(()=>mode==='corrupt'?'WRONG':data.get(k))},delete(k){calls.push('delete');return op(()=>data.delete(k))},getAll(){return op(()=>[...data.values()])}});tx.abort=()=>{clearTimeout(timer);tx.onabort?.()};return tx}};dbs.set(name,db)}req.result=db;if(fresh)req.onupgradeneeded?.();req.onsuccess?.()},0);return req}};return api;
}
function env(opts={}){const events=[],workers=[],handlers=new Map(),gpu=opts.gpu===false?undefined:{requestAdapter:async()=>opts.adapter===false?null:{features:new Set(opts.f16===false?[]:['shader-f16']),limits:{maxBufferSize:1073741824,maxStorageBufferBindingSize:268435456},info:{vendor:'FIXTURE_NOT_HARDWARE'}}};
 const location=new URL(opts.url||'https://fixture.invalid/course/index.html');const ctx={console,URL,performance,Date,JSON,Map,Set,Promise,Uint8Array,ArrayBuffer,TextEncoder,TextDecoder,AbortController,DOMException,crypto:global.crypto,setTimeout,clearTimeout,setInterval,clearInterval,structuredClone,location,isSecureContext:opts.secure!==false,navigator:{gpu,userAgent:'UNIT_FIXTURE_NOT_BROWSER',platform:'fixture',deviceMemory:opts.memory??8,onLine:opts.online!==false,storage:{estimate:async()=>({quota:10e9,usage:1e9}),persisted:async()=>false}},indexedDB:idbFixture(opts.idb||'normal'),document:{currentScript:{src:'https://fixture.invalid/course/genie/config.js'},baseURI:location.href,permissionsPolicy:null},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail}},addEventListener(type,f){if(!handlers.has(type))handlers.set(type,[]);handlers.get(type).push(f)},dispatchEvent(e){events.push(e);for(const f of handlers.get(e.type)||[])f(e)}};
 ctx.window=ctx;ctx.globalThis=ctx;ctx.top=ctx;ctx.self=ctx;ctx.parent=ctx;
 class WorkerFixture{constructor(url,options){if(opts.worker==='throw')throw Error('Worker fixture construction failed');this.url=url;this.options=options;this.terminated=false;workers.push(this)}postMessage(m){this.messages=(this.messages||[]).concat(m);const send=(kind,value)=>{if(!this.terminated)this.onmessage?.({data:{id:m.id,kind,value}})};
 if(m.type==='probe'){setTimeout(()=>this.onmessage?.({data:{probeVersion:'7.2.1',worker:true,adapterObtained:opts.workerGPU!==false,webgpu:!!gpu,f16:opts.f16!==false}}),0);return}
 if(m.type==='init'){if(opts.init==='hang')return;setTimeout(()=>{if(opts.init==='error'){this.onmessage?.({data:{id:m.id,kind:'error',error:{message:'fetch failed fixture',stage:'runtime'}}});return}const value={modelId:m.model,providerKind:'local-llm',liveInference:true,worker:true,adapterObtained:true,smoke:{responseNonEmpty:true,schemaValid:true,encodingValid:true},fixtureOnly:true};if(opts.omit){const keys=opts.omit.split('.');if(keys.length===2)value[keys[0]][keys[1]]=false;else value[keys[0]]=false}send('result',value)},0);return}
 if(m.type==='complete'){if(opts.complete==='hold'){this.active=m;return}setTimeout(()=>send('result',{content:'EXPLICIT UNIT FIXTURE, NOT GENERATED',model:'fixture',latencyMs:1,totalGenerationMs:1,firstTokenMs:1,worker:true}),0);return}
 if(m.type==='interrupt'){if(opts.cancel==='hang')return;if(this.active){const id=this.active.id;setTimeout(()=>this.onmessage?.({data:{id,kind:'error',error:{message:'Unit cancellation fixture',name:'AbortError'}}}),10);this.active=null}return}
 if(m.type==='cache')send('result',{value:false,fixtureOnly:true});
 if(m.type==='deleteCache')send('result',{deletedModel:'fixture',reportsTouched:false});
 }terminate(){this.terminated=true}}
 ctx.Worker=WorkerFixture;vm.createContext(ctx);for(const f of ['genie/config.js','genie/GenieCapabilityProbe.js','genie/RuntimeDiagnostics.js','genie/LocalModelProvider.js','genie/ModelProvider.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),ctx,{filename:f});return{ctx,G:ctx.GeniusMath,events,workers};
}
async function main(){
 for(const [name,opts,id]of [['file',{url:'file:///tmp/index.html'},'origin'],['insecure',{url:'http://example.test/',secure:false},'origin'],['no_gpu',{gpu:false},'webgpu'],['no_adapter',{adapter:false},'adapter'],['worker_blocked',{worker:'throw'},'worker'],['worker_gpu_missing',{workerGPU:false},'worker'],['idb_blocked',{idb:'blocked'},'indexedDB'],['idb_throw',{idb:'throw'},'indexedDB'],['idb_corruption',{idb:'corrupt'},'indexedDB']]){const e=env(opts),r=await e.G.GenieCapabilityProbe.probe();check('capability_'+name,!r.supported&&r.checks.some(x=>x.id===id&&x.status==='fail'));check('capability_remedy_'+name,r.checks.filter(x=>x.required&&x.status==='fail').every(x=>x.remedy&&x.continueWithoutAI));check('no_init_on_probe_'+name,!e.workers.some(w=>w.messages?.some(m=>m.type==='init')))}
 for(const url of ['https://example.test','http://localhost:8000','http://127.0.0.1:8000','http://[::1]:8000']){const e=env({url}),r=await e.G.GenieCapabilityProbe.probe();check('allowed_origin_'+url,r.supported)}
 const e=env(),cap=await e.G.GenieCapabilityProbe.probe();check('idb_lifecycle_invoked',['open','write','read','delete','close','deleteDatabase'].every(k=>e.ctx.indexedDB.calls.includes(k)));check('probe_no_grade_fields',!JSON.stringify(cap).includes('student_id'));check('unknown_vram_not_measured',cap.measurementUnavailableReason.freeVRAM&&cap.freeVRAM===undefined);check('profile_not_pedagogical_default',cap.recommendation.recommendedDefault===null);check('moderate_hardware_profile',cap.recommendation.profile==='standard');check('unknown_hardware_conservative',e.G.GenieCapabilityProbe.recommendProfile({}).profile==='light');check('high_hardware_trial',e.G.GenieCapabilityProbe.recommendProfile({deviceMemoryGB:16,adapter:{limits:{maxBufferSize:1073741824,maxStorageBufferBindingSize:268435456}},storage:{availableBytes:8e9}}).profile==='advanced');
 const offline=await env({online:false}).G.GenieCapabilityProbe.probe();check('offline_distinguished',offline.checks.some(x=>x.id==='online'&&x.status==='warning'));
 const ac=new AbortController();ac.abort();try{await e.G.GenieCapabilityProbe.probe({signal:ac.signal});check('cancel_probe',false)}catch(x){check('cancel_probe',x.name==='AbortError')}
 try{await e.G.GenieCapabilityProbe.idbTest(idbFixture('hang'),{timeoutMs:8});check('idb_timeout_bounded',false)}catch(x){check('idb_timeout_bounded',/respondió/.test(x.message))}
 const diag=[['network',Error('Failed to fetch'),'runtime','RUNTIME_IMPORT_FAILED'],['weights',Error('Failed to fetch'),'weights','RESOURCE_ACCESS_FAILED'],['storage',Error('QuotaExceededError'),'weights','STORAGE_FAILURE'],['device',Error('GPU device lost'),'generation','GPU_RESOURCE_FAILURE'],['time',Object.assign(Error('time'),{code:'TIMEOUT'}),'generation','OPERATION_TIMEOUT'],['protocol',Error('Smoke JSON inválido'),'warming','MODEL_PROTOCOL_FAILED'],['cancel',Object.assign(Error('cancel'),{name:'AbortError'}),'warming','CANCELLED']];
 for(const[n,error,stage,code]of diag){const d=e.G.RuntimeDiagnostics.classify(error,stage);check('diagnostic_'+n,d.code===code);check('diagnostic_action_'+n,!!d.cause&&!!d.remedy&&!!d.impact&&d.continueWithoutAI)}
 const offenv=env({online:false});check('network_offline_specific',offenv.G.RuntimeDiagnostics.classify(Error('Failed to fetch'),'runtime').code==='OFFLINE_RESOURCE_ACCESS');
 for(const omit of ['liveInference','providerKind','modelId','worker','adapterObtained','smoke.responseNonEmpty','smoke.schemaValid','smoke.encodingValid']){const x=env({omit}),p=new x.G.LocalModelProvider();try{await p.initialize('light');check('reject_incomplete_proof_'+omit,false)}catch(err){check('reject_incomplete_proof_'+omit,!p.ready&&!p.liveInference&&p.status==='error')}p.dispose()}
 const x=env({f16:false}),p=new x.G.LocalModelProvider();await p.initialize('light');check('f32_fallback_selected',p.model.includes('q4f32'));check('ready_after_proof_only',p.ready&&p.liveInference&&p.lastLoad.fixtureOnly);check('worker_module_requested',x.workers.at(-1).options.type==='module');check('no_ready_during_loading',x.events.filter(e=>e.type==='genius:model-state'&&['loading','probing','warming'].includes(e.detail.status)).every(e=>!e.detail.liveInference));const reply=await p.complete([{role:'user',content:'unit transport'}]);check('complete_transport',reply.content.startsWith('EXPLICIT UNIT FIXTURE'));check('provider_remains_ready_after_complete',p.status==='ready');const same=await p.initialize('light');check('reuse_ready_instance',same.reuseReadyInstance===true);p.dispose();check('dispose_clears_inference',!p.ready&&!p.liveInference&&p.providerKind==='uninitialized');
 const ce=env({complete:'hold'}),cp=new ce.G.LocalModelProvider();await cp.initialize('light');const task=cp.complete([{role:'user',content:'unit cancel'}]).then(()=>null,e=>e);cp.cancel();check('cancel_barrier_no_early_ready',cp.status==='cancelling'&&cp.pending.size===1);try{await cp.complete([{role:'user',content:'race'}]);check('no_parallel_after_cancel',false)}catch(_){check('no_parallel_after_cancel',true)}const cancelled=await task;check('cancel_ack_waited',cancelled.name==='AbortError'&&cp.status==='ready');cp.dispose();
 const te=env({complete:'hold',cancel:'hang'}),tp=new te.G.LocalModelProvider();te.G.config.localModel.cancelTimeoutMs=10;await tp.initialize('light');const tt=tp.complete([{role:'user',content:'unresponsive fixture'}]).catch(e=>e);tp.cancel();await tt;check('stuck_worker_terminated',!tp.ready&&!tp.liveInference&&te.workers.at(-1).terminated);tp.dispose();
 const ie=env({init:'hang'}),ip=new ie.G.LocalModelProvider();ie.G.config.localModel.loadTimeoutMs=25;const it=ip.initialize('light').catch(e=>e);await delay(16);ip.cancel();const cancelInit=await it;check('init_cancel_does_not_activate',!ip.ready&&!ip.liveInference&&cancelInit.name==='AbortError');
 const ee=env({init:'error'}),ep=new ee.G.LocalModelProvider();try{await ep.initialize('light')}catch(_){}check('runtime_error_cause_visible',ep.diagnostic.code==='RUNTIME_IMPORT_FAILED'&&/runtime/.test(ep.lastError));check('error_does_not_activate',!ep.liveInference);
 const be=env();for(const f of ['validation/benchmark_cases.js','validation/benchmark_v721_cases.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),be.ctx);const B=be.ctx.GeniusBenchmarkV721;
 for(const [stage,count]of Object.entries(B.expected))check('benchmark_count_'+stage,B.cases(stage).length===count);check('benchmark_long_24',B.cases('C').every(c=>c.profile.messages.length===24));check('formula_regression_included',B.regression.includes('dame la formula que se me pide'));check('benchmark_no_fake_gate',!B.gate({stage:'A',model:'x',conversations:[]},'A','x').passed);check('human_scores_not_invented',Object.values(B.emptyReview().scores).every(x=>x===null));
 const result={version:'7.2.1-rc1',executed:true,kind:'UNIT_API_FIXTURES_ONLY',liveInferenceExecuted:false,realBrowserGPU:false,total:rows.length,passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass),results:rows};fs.writeFileSync(path.join(__dirname,'RUNTIME_UNIT_RESULTS_V721.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,results:undefined},null,2));process.exitCode=result.failed.length?1:0;
}
main().catch(e=>{console.error(e);process.exitCode=1});
