/* Infrastructure tests. Scripted provider fixtures are NOT model benchmarks. */
'use strict';const fs=require('fs'),path=require('path'),vm=require('vm');const ROOT=path.resolve(__dirname,'..');global.window=global;global.dispatchEvent=()=>{};global.CustomEvent=class{constructor(type,opts){this.type=type;this.detail=opts?.detail}};
for(const f of ['bank/base_bank.js','bank/extended_bank.js','questions.js','genie/config.js','genie/FormulaCatalog.js','genie/QuestionMetadata.js','genie/FormulaCoach.js','genie/PedagogyEngine.js','genie/TransferCatalog.js','genie/StudentModel.js','genie/GenieMemory.js','genie/AlgebraVerifier.js','genie/EvaluatorBridge.js','genie/ContextBridge.js','genie/PromptContract.js','genie/ToolRegistry.js','genie/LoopDetector.js','genie/OutputGuard.js','genie/GuidedProvider.js','genie/LocalModelProvider.js','genie/CloudModelProvider.js','genie/ModelProvider.js','genie/GenieEngine.js','genie/ReportBridge.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,f),'utf8'),{filename:f});
const G=GeniusMath,Q=PokerQuestions.all(),results=[];function check(name,pass,details={},category='unit'){results.push({name,pass:!!pass,category,...details})};
const evalQ=(q,x)=>q.type==='mcq'?String(x)===q.answer:Math.abs(Number(x)-q.answer)<(q.tolerance||1e-8);G.EvaluatorBridge.register({evaluate:evalQ});
function cycle(q){return{qId:q.id,phase:'genie',submitted:false,startedAt:1,learning:{genie:{threadId:'fixture:'+q.id,turns:[],summary:'',studentModel:G.StudentModel.create(),interventions:[]}}}}
const baseReply=(o={})=>({action:'reply',tool:'',args:{},text:'Texto de fixture para comprobar el transporte; no es una respuesta de IA.',student_state:'unknown',confidence:.2,strategy:'explanation',concepts:[],formula_ids:[],errors:[],summary:'Resumen de prueba',semantic_key:'fixture',needs_new_strategy:false,claims_correct:false,verification_scope:'none',...o});
async function main(){check('original_bank_count',Q.length===500,{actual:Q.length});check('unique_ids',new Set(Q.map(q=>q.id)).size===500);check('supplements_only',G.TransferCatalog.all().length===4&&Q.every(q=>q.id.startsWith('EDO-C3-')));
 for(const q of Q){const p=G.PedagogyEngine.profile(q);check('metadata:'+q.id,p.formulaIds.every(id=>!!G.FormulaCatalog.get(id))&&!!p.conceptKey);check('reference_structure:'+q.id,q.type==='mcq'?q.options.includes(q.answer)&&new Set(q.options).size===q.options.length:Number.isFinite(q.answer));const t=G.PedagogyEngine.selectTransfer(q,[q.id]);check('transfer:'+q.id,t&&!!G.PedagogyEngine.transferInfo(q,t),{target:t?.id,concept:p.conceptKey});const c=G.ContextBridge.build({question:q,cycle:cycle(q),studentMessage:'¿Por qué?'});const keys=new Set();function scan(o){if(o&&typeof o==='object'){for(const k of Object.keys(o)){keys.add(k);scan(o[k])}}}scan(c);check('context_separation:'+q.id,!['answer','solution','explanation','hint','canonicalAnswer','bank'].some(k=>keys.has(k))&&c.problem.id===q.id);}
 for(const q of Q){const t=G.PedagogyEngine.selectTransfer(q,Q.map(x=>x.id));check('transfer_pool_exhausted:'+q.id,!!t&&t.id!==q.id)}
 for(let a=-4;a<=4;a++)for(let b=-4;b<=4;b++)if(a!==b){const left=`1/((s+(${a}))*(s+(${b})))`,right=`(1/(s+(${a}))-1/(s+(${b})))/(${b-a})`;const r=G.AlgebraVerifier.identity(left,right);check(`partial_fraction:${a}:${b}`,r.status==='verified',{},'exact_math')}
 for(let a=-20;a<=20;a++){check('minus_sign:'+a,G.AlgebraVerifier.identity(`-(s-(${a}))`,`-s+(${a})`).status==='verified',{},'exact_math');if(a)check('wrong_sign:'+a,G.AlgebraVerifier.identity(`-(s-(${a}))`,`-s-(${a})`).status==='not_identity',{},'exact_math')}
 for(const [work,status]of [['2x+2=4\n2x=2\nx=1','verified'],['2x+2=4\n2x=6','not_equivalent'],['x^2=0\nx=0','unknown'],['x^2=1\nx=1','not_equivalent'],['sin(x)=x','unknown'],['1/0=2','unknown'],['0^0=1','unknown'],['alert(1)=1','unknown'],['x/x=1\n1=1','unknown']])check('work:'+work,G.AlgebraVerifier.work(work).status===status,{actual:G.AlgebraVerifier.work(work).status},'exact_math');
 const q=PokerQuestions.get('EDO-C3-014'),c=cycle(q);let evidence=[],tools=G.ToolRegistry.create({question:q,cycle:c,message:'1/(s*(s+1))=1/s-1/(s+1)',evidence});check('tool_literal_work',tools.run('evaluateStudentStep',{work:'1/(s*(s+1))=1/s-1/(s+1)'}).status==='verified');check('tool_fabricated_work_rejected',tools.run('evaluateStudentStep',{work:'2=2'}).status==='unknown');check('tool_unknown_denied',tools.run('fetch',{id:'secret'}).status==='denied');check('tool_transfer_hidden',tools.run('selectTransferProblem',{}).available===false);c.phase='transfer';check('tool_phase_closed',tools.run('getRelevantFormula',{}).status==='denied');
 check('guard_correctness',!G.OutputGuard.check(baseReply({text:'Tu respuesta es correcta.',claims_correct:true,verification_scope:'answer'}),q,[]).ok);check('guard_step_cannot_certify_answer',!G.OutputGuard.check(baseReply({text:'Tu respuesta es correcta.',claims_correct:true,verification_scope:'answer'}),q,[{tool:'evaluateStudentStep',result:{status:'verified'}}]).ok);check('guard_algebra_scope',G.OutputGuard.check(baseReply({text:'La identidad algebraica escrita se verifica; esto no valida las condiciones del problema.',claims_correct:true,verification_scope:'algebra_step'}),q,[{tool:'evaluateStudentStep',result:{status:'verified'}}]).ok);check('guard_answer_letter',!G.OutputGuard.check(baseReply({text:'La opción es C.'}),q,[]).ok);check('guard_internal_label',!G.OutputGuard.check(baseReply({text:'off_topic: confianza 0.8'}),q,[]).ok);check('guard_formula_allowed',G.OutputGuard.check(baseReply({text:'Recuerda [[formula:shift_s]]',formula_ids:['shift_s']}),q,[]).ok);check('guard_formula_irrelevant',!G.OutputGuard.check(baseReply({text:'[[formula:rlc]]',formula_ids:['rlc']}),q,[]).ok);
 let sm=G.StudentModel.create();for(let i=0;i<3;i++)sm=G.StudentModel.update(sm,baseReply({needs_new_strategy:i>0}));check('strategy_after_two_failures',G.PedagogyEngine.intervention(sm,[{strategy:'explanation'}]).mustChange);
 let r=await G.LoopDetector.inspect(baseReply({text:'La idea es usar la fórmula.'}),[{role:'assistant',text:'La idea es usar la fórmula.'}],null,'¿por qué?');check('loop_exact',r.duplicate&&r.method==='exact');
 const judgeFixture={complete:async()=>({content:JSON.stringify({equivalent:true,similarity:.97})})};r=await G.LoopDetector.inspect(baseReply({text:'La transformación depende de esa propiedad.'}),[{role:'assistant',text:'Se aplica el mismo principio operacional.'}],judgeFixture,'¿por qué?');check('loop_semantic_rpc_fixture',r.duplicate&&r.method==='model_semantic_judge',{},'provider_fixture_not_inference');
 const old=G.ModelProvider.current();G.ModelProvider.useGuided();try{await G.GenieEngine.ask({question:q,cycle:cycle(q),message:'Hola'});check('no_fake_ai',false)}catch(e){check('no_fake_ai',/Activa/.test(e.message))}
 let calls=0;const fixture={kind:'test_fixture_not_ai',generative:true,ready:true,complete:async()=>({content:JSON.stringify(baseReply({text:'Fixture de transporte número '+(++calls)+'.'})),latencyMs:null})};G.ModelProvider.set(fixture);const cx=cycle(q);const gr=await G.GenieEngine.ask({question:q,cycle:cx,message:'mensaje de prueba'});check('engine_rpc_fixture',gr.text.includes('Fixture')&&gr.penalty===0&&cx.learning.genie.interactions===1,{},'provider_fixture_not_inference');cx.phase='transfer';try{await G.GenieEngine.ask({question:q,cycle:cx,message:'ayuda'});check('engine_transfer_blocked',false)}catch(e){check('engine_transfer_blocked',true)}
 let repeatCalls=0;const loopFixture={kind:'anti_loop_fixture_not_ai',ready:true,generative:true,complete:async(messages,opts)=>{if(opts.schema.properties.equivalent)return{content:JSON.stringify({equivalent:false,similarity:.05})};repeatCalls++;return{content:JSON.stringify(baseReply({text:repeatCalls===1?'Explicación repetida de fixture.':'Representación alternativa comprobada solo como flujo de prueba.',strategy:repeatCalls===1?'explanation':'concrete_example'}))}}};G.ModelProvider.set(loopFixture);const lc=cycle(q);lc.learning.genie.turns=[{role:'assistant',text:'Explicación repetida de fixture.'}];const lr=await G.GenieEngine.ask({question:q,cycle:lc,message:'No entendí'});check('loop_regenerate_transport_fixture',repeatCalls===2&&lr.analytics.loop_prevented===1&&lr.strategy==='concrete_example',{},'provider_fixture_not_inference');
 const t=G.TransferCatalog.all()[0];check('pending_transfer_report',G.ReportBridge.transferHTML({transfer:{id:t.id,submitted:false,correct:null}}).includes('pendiente'));check('report_internal_labels_removed',!G.ReportBridge.questionHTML({genius:{turns:1,offTopic:3,extractionAttempts:5}}).match(/off_topic|extracción|penalización/));
 G.ModelProvider.set(old);const out={version:'7.2.1-rc1',kind:'infrastructure_and_exact_math',executed:true,liveModelInference:false,total:results.length,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass),categories:Object.fromEntries([...new Set(results.map(x=>x.category))].map(c=>[c,results.filter(x=>x.category===c).length])),results};fs.writeFileSync(path.join(__dirname,'CORE_TEST_RESULTS.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({total:out.total,passed:out.passed,failed:out.failed,categories:out.categories},null,2));process.exitCode=out.failed.length?1:0;}
main().catch(e=>{console.error(e);process.exitCode=1});
