/* Exact shipped SCORM adapter in a VM with explicit API fixtures. Not a real LMS. */
'use strict';const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..'),code=fs.readFileSync(path.join(root,'scorm.js'),'utf8'),rows=[];function check(name,pass,detail){rows.push({name,pass:!!pass,...(detail||{})})}
function setup(overrides={},behavior={}){const values={'cmi.core.student_name':'Alumno Fixture','cmi.core.student_id':'TEST-ONLY','cmi.core.lesson_mode':'normal','cmi.core.lesson_status':'not attempted',...overrides},log=[],ctx={console,TextEncoder,Date,addEventListener:()=>{}};ctx.window=ctx;ctx.parent=ctx;ctx.API={LMSInitialize:()=>{log.push(['initialize']);return behavior.init===false?'false':'true'},LMSGetValue:k=>values[k]||'',LMSSetValue:(k,v)=>{log.push(['set',k,v]);values[k]=v;return 'true'},LMSCommit:()=>{log.push(['commit']);return behavior.commit===false?'false':'true'},LMSFinish:()=>{log.push(['finish']);return behavior.finish===false?'false':'true'},LMSGetLastError:()=> '0'};vm.createContext(ctx);vm.runInContext(code,ctx);return{sc:ctx.POKER_SCORM,values,log,behavior}}
let x=setup();check('initialize_returns_success',x.sc.init());check('initialization_once',x.sc.init()&&x.log.filter(r=>r[0]==='initialize').length===1);check('name_from_api',x.sc.studentName==='Alumno Fixture');check('id_from_api',x.sc.studentId==='TEST-ONLY');check('profile_tracked_student',x.sc.getProfile()==='student');check('new_activity_incomplete',x.values['cmi.core.lesson_status']==='incomplete');check('initial_commit',x.log.some(r=>r[0]==='commit'));check('begin_attempt',x.sc.beginAttempt());check('suspend_save_committed',x.sc.save(null,{v:10,g:2.4,c:4,cq:{qId:'fixture',phase:'transfer'}}));check('suspend_load_roundtrip',x.sc.loadSuspend().cq.phase==='transfer');check('resume_does_not_complete',x.sc.getAttempt().completed===false);check('score_clamped_low',x.sc.setScore(-5)===0&&x.values['cmi.core.score.raw']==='0.00');check('score_clamped_high',x.sc.setScore(10)===5&&x.values['cmi.core.score.raw']==='5.00');check('scale_0_5',x.values['cmi.core.score.min']==='0'&&x.values['cmi.core.score.max']==='5');check('finish_pass',x.sc.finish(3.4,{fin:true,fg:3.4}));check('status_passed',x.values['cmi.core.lesson_status']==='passed');check('final_score',x.values['cmi.core.score.raw']==='3.40');check('completed_attempt_recognized',x.sc.getAttempt().completed===true);check('finish_once',x.sc.finish(3.4,{fin:true})&&x.log.filter(r=>r[0]==='finish').length===1);check('session_time_format',/^\d+:\d{2}:\d{2}$/.test(x.values['cmi.core.session_time']));
x=setup();x.sc.init();check('finish_failed_grade_closes',x.sc.finish(2.2,{fin:true}));check('status_failed',x.values['cmi.core.lesson_status']==='failed');
x=setup({'cmi.core.student_name':'Without Tracking, Preview','cmi.core.lesson_mode':'browse'});check('preview_initializes_readonly',x.sc.init());check('without_profile',x.sc.getProfile()==='teacher_without');x.sc.beginAttempt();x.sc.save(4,{v:10});x.sc.finish(4,{fin:true});check('preview_no_writes_commits_finish',x.log.every(r=>!['set','commit','finish'].includes(r[0])));check('preview_not_completed',x.sc.getAttempt().completed===false);
x=setup({}, {init:false});check('init_failure_reported',!x.sc.init());check('no_writes_when_init_failed',x.log.every(r=>r[0]==='initialize'));
x=setup({}, {commit:false});x.sc.init();check('save_reports_commit_failure',!x.sc.save(null,{v:10}));check('commit_status_failure',x.sc.lastCommitOk===false);
x=setup({}, {finish:false});x.sc.init();check('finish_failure_not_completed_flag',!x.sc.finish(4,{fin:true})&&!x.sc.finished);x.behavior.finish=true;check('finish_retry',x.sc.finish(4,{fin:true})&&x.sc.finished);
x=setup();x.sc.init();const long={v:10,g:3,le:'x'.repeat(10000)};check('oversize_optional_event_compacted',x.sc.save(null,long)&&Buffer.byteLength(x.values['cmi.suspend_data'],'utf8')<=3800);const huge={v:10,cq:{extra:'á'.repeat(5000)}};check('oversize_required_state_not_silently_truncated',!x.sc.save(null,huge));
const out={version:'7.2.2-safe-audited',kind:'EXACT_ADAPTER_WITH_EXPLICIT_LMS_API_FIXTURES',executed:true,realBrightspaceExecuted:false,liveInferenceExecuted:false,total:rows.length,passed:rows.filter(r=>r.pass).length,failed:rows.filter(r=>!r.pass),results:rows,limitations:['SetValue/Commit/Finish acknowledgements are fixture values. No institutional gradebook was queried.','No SCORM 1.2 XSD or certification suite was available.']};fs.writeFileSync(path.join(__dirname,'SCORM_API_TEST_RESULTS_V721.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({...out,results:undefined},null,2));if(out.failed.length)process.exitCode=1;
