/* Deep structural/pedagogical audit for v7.2.2 safe build. Does NOT claim live LLM inference. */
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'..');global.window=global;global.dispatchEvent=()=>{};global.CustomEvent=class{constructor(t,o){this.type=t;this.detail=o?.detail}};
for(const f of ['bank/base_bank.js','bank/extended_bank.js','questions.js','genie/config.js','genie/FormulaCatalog.js','genie/QuestionMetadata.js','genie/FormulaCoach.js','genie/PedagogyEngine.js','genie/TransferCatalog.js','genie/StudentModel.js','genie/PromptContract.js','genie/ContextBridge.js','genie/OutputGuard.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,f),'utf8'),{filename:f});
const G=GeniusMath,Q=PokerQuestions.all(),raw=ECOMAT_EXTENDED.generateBank('POKER-MATH-EDO-CORTE3-500-2026-2'),rows=[];
function check(name,pass,detail={}){rows.push({name,pass:!!pass,...detail})}
const count=(xs,key)=>Object.fromEntries([...new Set(xs.map(x=>x[key]))].sort().map(k=>[String(k),xs.filter(x=>x[key]===k).length]));
check('safe_version',G.config.version==='7.2.2-safe-audited',{actual:G.config.version});
check('only_one_local_profile',Object.keys(G.config.profiles).length===1&&!!G.config.profiles.light,{profiles:Object.keys(G.config.profiles)});
check('only_qwen_06b_exposed',/0\.6B/.test(G.config.profiles.light.model)&&!/1\.7B|4B/.test(JSON.stringify(G.config.profiles)));
check('safe_context_window',G.config.localModel.contextWindowSize<=1280,{actual:G.config.localModel.contextWindowSize});
check('safe_output_tokens',G.config.localModel.hardMaxOutputTokens<=160&&G.config.maxOutputTokens<=144,{hard:G.config.localModel.hardMaxOutputTokens,max:G.config.maxOutputTokens});
check('safe_no_regeneration',G.config.maxRegenerations===0&&G.config.maxToolRounds===0&&G.config.localModel.semanticLoopJudge===false);
check('safe_requires_f16',G.config.localModel.requireF16===true);
check('prompt_schema_compact',JSON.stringify(G.PromptContract.safeSchema).length<700&&G.PromptContract.safeSchema.required.length<=6,{chars:JSON.stringify(G.PromptContract.safeSchema).length,required:G.PromptContract.safeSchema.required});
check('bank_500',Q.length===500,{actual:Q.length});check('raw_bank_500',raw.length===500,{actual:raw.length});check('unique_ids',new Set(Q.map(q=>q.id)).size===500);check('raw_unique_ids',new Set(raw.map(q=>q.id)).size===500);
const expectedSource={multiple_choice:125,true_false:75,numeric:75,statements:75,ordering:75,graphic:75};const actualSource=count(Q,'sourceType');check('source_type_distribution',Object.keys(expectedSource).every(k=>actualSource[k]===expectedSource[k])&&Object.keys(actualSource).every(k=>k in expectedSource),{actual:actualSource});
check('normal_rescue_distribution',Q.filter(q=>q.difficulty==='normal').length===458&&Q.filter(q=>q.difficulty==='rescue').length===42);
const sourceErrors=ECOMAT_EXTENDED.validateBank(raw);check('source_bank_validator',sourceErrors.length===0,{errors:sourceErrors.slice(0,10)});
let rawStructural=[];for(const q of raw){if(!q.id||!q.prompt||!q.hint||!q.explanation)rawStructural.push([q.id,'missing_text']);if(/<script|javascript:/i.test(q.prompt+q.hint+q.explanation))rawStructural.push([q.id,'unsafe_markup']);if(q.type==='numeric'){if(!Number.isFinite(Number(q.answer?.value))||Number(q.answer?.tolerance)<0)rawStructural.push([q.id,'numeric_answer'])}else if(q.type==='true_false'){if(typeof q.answer?.value!=='boolean')rawStructural.push([q.id,'boolean_answer'])}else{if(!Array.isArray(q.choices)||q.choices.length<2||new Set(q.choices.map(String)).size!==q.choices.length||!Number.isInteger(q.answer?.index)||q.answer.index<0||q.answer.index>=q.choices.length)rawStructural.push([q.id,'choice_structure'])}if(q.type==='ordering'&&!q.choices?.every(x=>String(x).includes('→')))rawStructural.push([q.id,'ordering_format']);if(q.graphic&&!ECOMAT_BANK.GRAPHICS[q.graphic])rawStructural.push([q.id,'graphic_registry'])}
check('raw_question_structure_all_500',rawStructural.length===0,{issues:rawStructural.slice(0,20)});
let adaptedStructural=[],metadataErrors=[],contextLeaks=[],transferErrors=[],emergencyErrors=[],budgetErrors=[],contextJsonErrors=[],guardLeaks=[],graphicErrors=[],fallbackMath=[];let strictTransferCount=0,emergencyFallbackCount=0;
for(const q of Q){
 if(!q.id||!q.prompt||!q.hint||!q.explanation)adaptedStructural.push([q.id,'missing']);
 if(q.type==='mcq'){if(!Array.isArray(q.options)||q.options.length<2||!q.options.includes(q.answer)||new Set(q.options).size!==q.options.length)adaptedStructural.push([q.id,'mcq'])}
 else if(q.type==='numeric'){if(!Number.isFinite(q.answer)||!Number.isFinite(q.tolerance)||q.tolerance<0)adaptedStructural.push([q.id,'numeric'])}else adaptedStructural.push([q.id,'unsupported:'+q.type]);
 if(q.hasGraphic){if(!q.graphicSrc||!fs.existsSync(path.join(ROOT,q.graphicSrc)))graphicErrors.push([q.id,q.graphicSrc]);}
 let p;try{p=G.PedagogyEngine.profile(q);if(!p.objective||!p.conceptKey||!p.formulaIds.every(id=>!!G.FormulaCatalog.get(id)))metadataErrors.push([q.id,'metadata'])}catch(e){metadataErrors.push([q.id,e.message]);continue}
 const cyc={phase:'genie',submitted:false,startedAt:1,learning:{genie:{turns:[{role:'student',text:'x'.repeat(900)},{role:'assistant',text:'y'.repeat(1800),strategy:'explanation'}],summary:'s'.repeat(520),studentModel:G.StudentModel.create(),interventions:[]}}};
 const c=G.ContextBridge.build({question:q,cycle:cyc,studentMessage:'z'.repeat(900)});const keys=new Set();(function scan(o){if(o&&typeof o==='object'){for(const k of Object.keys(o)){keys.add(k);scan(o[k])}}})(c);if(['answer','solution','explanation','hint','canonicalAnswer','bank'].some(k=>keys.has(k)))contextLeaks.push(q.id);
 const ms=G.ContextBridge.messages(c,cyc),chars=ms.reduce((a,m)=>a+m.content.length,0);if(chars>G.config.contextCharBudget)budgetErrors.push([q.id,chars]);const dm=ms.find(m=>m.content.startsWith('DATOS DEL EJERCICIO'));if(dm){try{JSON.parse(dm.content.split('\n').slice(1).join('\n'))}catch(e){contextJsonErrors.push([q.id,e.message])}}else contextJsonErrors.push([q.id,'missing-data-message']);
 const t=G.PedagogyEngine.selectTransfer(q,[q.id]);
 if(t&&t.id!==q.id&&G.PedagogyEngine.transferInfo(q,t)) strictTransferCount++;
 else {const em0=G.PedagogyEngine.selectEmergencyTransfer(q,[q.id]);if(em0&&em0.id!==q.id&&em0.topic===q.topic) emergencyFallbackCount++; else transferErrors.push([q.id,t?.id,em0?.id]);}
 // Exhausted-used-pool scenario: strict selector may reuse a valid conceptual transfer; otherwise emergency same-topic fallback must prevent deadlock.
 const te=G.PedagogyEngine.selectTransfer(q,Q.map(x=>x.id));const em=G.PedagogyEngine.selectEmergencyTransfer(q,Q.map(x=>x.id));
 if(te){if(te.id===q.id||!G.PedagogyEngine.transferInfo(q,te))transferErrors.push([q.id,'bad-strict-exhausted',te.id]);}
 else if(!em||em.id===q.id||em.topic!==q.topic)transferErrors.push([q.id,'no-transfer-exhausted',em?.id]);
 if(!em||em.id===q.id||em.topic!==q.topic)emergencyErrors.push([q.id,em?.id]);
 const direct=q.type==='mcq'?`La respuesta del ejercicio es ${q.answer}.`:`El valor de la respuesta es ${q.answer}.`;const r={text:direct,strategy:'explanation',summary:'',semantic_key:'leak',claims_correct:false,verification_scope:'none'};if(G.OutputGuard.check(r,q,[]).ok)guardLeaks.push([q.id,q.answer]);
 const sf=G.PedagogyEngine.safeFallback(q,'No recuerdo la fórmula','explanation');if(p.formulaIds.length&&(!sf.includes('\\[')||!sf.includes('\\]')))fallbackMath.push(q.id);
}
check('adapted_structure_all_500',adaptedStructural.length===0,{issues:adaptedStructural.slice(0,20)});check('all_graph_assets_exist',graphicErrors.length===0,{issues:graphicErrors});check('metadata_all_500',metadataErrors.length===0,{issues:metadataErrors.slice(0,20)});check('context_no_hidden_answer_fields',contextLeaks.length===0,{ids:contextLeaks.slice(0,20)});check('context_budget_all_500',budgetErrors.length===0,{issues:budgetErrors.slice(0,20)});check('context_data_json_valid_all_500',contextJsonErrors.length===0,{issues:contextJsonErrors.slice(0,20)});check('transfer_or_emergency_all_500_even_pool_exhausted',transferErrors.length===0,{issues:transferErrors.slice(0,20),strictTransferCount,emergencyFallbackCount});check('emergency_transfer_all_500',emergencyErrors.length===0,{issues:emergencyErrors.slice(0,20)});check('direct_answer_leak_guard_all_500',guardLeaks.length===0,{issues:guardLeaks.slice(0,20)});check('safe_fallback_mathjax_delimiters',fallbackMath.length===0,{ids:fallbackMath.slice(0,20)});
// Student-model regression: one dissatisfied follow-up must count once, not twice.
let sm=G.StudentModel.create();sm.lastStrategy='explanation';sm=G.StudentModel.observeMessage(sm,'No entendí; más fácil.');const before=sm.unsuccessfulStrategies.explanation||0;sm=G.StudentModel.update(sm,{strategy:'concrete_example',text:'x',summary:'x',semantic_key:'x',formula_ids:[],concepts:[],errors:[],confidence:.2},'');check('student_failure_count_not_doubled',before===1&&(sm.unsuccessfulStrategies.explanation||0)===1,{before,after:sm.unsuccessfulStrategies.explanation});
// Source ordering inventory: unique choice sets and correct index; mathematical alternative-order equivalence still requires human review.
const ordering=raw.filter(q=>q.type==='ordering');check('ordering_75_structurally_unique',ordering.length===75&&ordering.every(q=>new Set(q.choices).size===q.choices.length&&q.choices[q.answer.index]===q.answer.display));
const result={version:G.config.version,kind:'DEEP_STATIC_STRUCTURAL_PEDAGOGICAL_AUDIT_NOT_LIVE_LLM',strictTransferCount,emergencyFallbackCount,executed:true,liveInferenceExecuted:false,realBrightspaceExecuted:false,total:rows.length,passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass),sourceTypeDistribution:count(Q,'sourceType'),limitations:['No live WebGPU inference was executed in this environment.','Structural validation of ordering items does not prove that no alternative pedagogically valid ordering exists.','Independent symbolic audit coverage is reported separately; this script does not certify every mathematical answer from first principles.'],results:rows};
fs.writeFileSync(path.join(__dirname,'DEEP_AUDIT_V722_RESULTS.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,results:undefined},null,2));if(result.failed.length)process.exitCode=1;
